### PR TITLE
ticket-1563 Fixed issue - IMA Agent trying to start transfer loop with unconnected chains

### LINKED ISSUE #1563: IMA Agent trying to start transfer loop with unconnected chains
**Environment**
IMA Agent: 2.0.0-beta.7
Network: [Regression](https://github.com/skalenetwork/internal-support/blob/main/docs/testing-space/test-environments/network-Regression/Regression.md)
Schain name: curly-red-alterf
Have at least one schain connected to check diff

**Step to reproduce**
- Update ima agent to version 2.0.0-beta.9
- Observe IMA Agent logs

**Actual result** 
Agent try's to call getIncomingMessagesCounter and get revert because schain are not connected. 

**Expected result**
Agent shouldn't msg loop between unconnected chains 

**Log**
2023-08-18 20:07:38.935: Querying via URL http://34.217.246.35:10323 to S-Chain howling-hoedus whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:38.948: Got false
2023-08-18 20:07:38.949: Querying via URL http://35.80.147.90:10131 to S-Chain portly-passionate-sirius whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:38.959: Got true
2023-08-18 20:07:38.959: Querying via URL http://54.245.123.63:10195 to S-Chain quiet-alchiba whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:38.969: Got true
2023-08-18 20:07:38.970: Querying via URL http://44.227.63.77:10195 to S-Chain green-giddy-denebola whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:38.983: Got false
2023-08-18 20:07:38.983: Querying via URL http://44.235.52.167:10323 to S-Chain wan-tasty-kitalpha whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:39.112: Got false
2023-08-18 20:07:39.112: Querying via URL http://34.217.241.119:10131 to S-Chain submissive-well-off-rotanev whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:39.127: Got false
2023-08-18 20:07:39.127: Querying via URL http://52.38.187.226:10387 to S-Chain lone-brisk-our-skale whether it's connected to S-Chain curly-red-alterf...
2023-08-18 20:07:39.138: Got false

**Full log** 
[imaGetOutgoing.txt](https://github.com/skalenetwork/IMA/files/12398015/imaGetOutgoing.txt)
ains

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**
Fixed issue - IMA Agent trying to start transfer loop with unconnected chains

### CODE REVIEW

**Review by badrogger — DISMISSED** [review]

File: npms/skale-observer/observer.mjs [hunk 1]
```diff
@@ -709,10 +708,41 @@ export async function loadSChainsConnectedOnly( strChainNameConnectedTo, opts )
...
+                        if( log.verboseGet() >= log.verboseReversed().error ) {
+                            opts.details.write( cc.error( "Failed attempt " ) +
+                                cc.info( idxAttempt ) + cc.error( " of " ) +
+                                cc.info( cntAttempts ) +
+                                cc.error( " to query connected state of " ) +
+                                cc.info( strSChainName ) + cc.debug( " and S-Chain, got error: " ) +
+                                cc.warning( owaspUtils.extractErrorMessage( err ) ) +
+                                cc.error( ", stack is: " ) + "\n" + cc.stack( err.stack ) + "\n" );
+                        }
+                    }
```
Comment (DmytroNazarenko) [inline npms/skale-observer/observer.mjs]: Please, move to a separate function to avoid code duplication

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]

**Review by kladkogex — APPROVED** [review]

**Review by badrogger — APPROVED** [review]

**Review by DmytroNazarenko — APPROVED** [review]
