### PR TITLE
Ticket-1584 Fixed re-discovery issues for own S-chain and connected S-chains

### LINKED ISSUE #1584: IMA Agent not refresh data in cache after init
**Description**
Transfer type: unrelated 
Network: Regression 
Components: 
IMA: 2.0.0-beta.9(or any)
At least 2(A,B)  schain on the network 

**Steps to reproduce**
Connect schains to each other  
Observe logs(i.e transfer loop s2s)

**Actual result**
Currently IMA Agent make discover network only after initialization 

**Expected result**
IMA Agent should refresh data before start work.

Required action: 
- discuss the frequency of data updates
- add logs for this action(i.e: {timestamp}{action start}{action end+result})

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**
- Fixed SNB parallel discovery delays for connected S-chains
- Fixed own S-chain discovery delays
- Added high-verbosity-trace level logs to detect re-discovery details

### CODE REVIEW

File: agent/discoveryTools.mjs [hunk 1]
```diff
@@ -251,13 +264,13 @@ export async function continueSChainDiscoveryInBackgroundIfNeeded( isSilentReDis
                         let strMessage =
                             cc.success( "S-Chain network was re-discovered, " ) +
                             cc.info( cntDiscoveredNew ) +
-                            cc.success( " of " ) + cc.info( cntNodes ) +
+                            cc.success( " of " ) + cc.info( nCountToWait ) +
                             cc.success( " node(s) (" ) + strDiscoveryStatus + cc.success( ")" );
-                        const cntStillUnknown = cntNodes - cntDiscoveredNew;
+                        const cntStillUnknown = nCountToWait - cntDiscoveredNew;
```
Comment (DmytroNazarenko) [inline agent/discoveryTools.mjs]: This could be negative number if the number of already discovered nodes will be more than 2/3

**Review by DmytroNazarenko — DISMISSED** [review]

File: agent/discoveryTools.mjs (hunk 1 above)
Comment (sergiy-skalelabs) [reply agent/discoveryTools.mjs]: Resolved

**Review by badrogger — APPROVED** [review]

**Review by DmytroNazarenko — APPROVED** [review]
