### PR TITLE
Ticket 737, switch IMA agent to to ethers.js in branch v1.6.0

### LINKED ISSUE #26: Separate logs for different log levels
We should have at lease two log levels like *info* and *debug*, *trace* . 
Info - should used in regular work 
Debug - during troubleshooting problems 

List of information what should be moved to debug level. 

- [ ] Full response from SNB requests
- [ ] BLS Glue information
- [ ] Information of collecting signatures

Note: additional points may be added later during final review

### LINKED ISSUE #737: IMA - switch to ethers.js
**ethers.js**  provides faster RPC call results to Ethereum clients then **web3.js** do. It's reasonable to switch **IMA Agent** app to **ethers.js**.

┆Issue is synchronized with this [Jiraserver Task](https://skalelabs.atlassian.net/browse/SKALE-4460)

### LINKED ISSUE #1248: IMA agent JS only
Remove `skale_imaVerfyAndSign` and other IMA-related JSON RPC APIs from **skaled** and implement them in **IMA Agent**. Provide **IMA Agent** with all required parameters for BLS-based message signing with **SGX Wallet**.

### LINKED ISSUE #1405: IMA Verify and Sign not work in parallel
**Preconditions**
Skaled: 
IMA:
 
 **Step to reproduce**
 Run IMA M2S transfer(any)
 
 
**Actual result**
After adding additional logs to IMA we see that IMA Verify and Sign not work in parallel. 

skalenetwork/ima:1.3.0-develop.11
skalenetwork/schain:3.14.9-stable.5

[sequence_request_from_ima-agent.log](https://github.com/skalenetwork/internal-support/files/8707545/sequence_request_from_ima-agent.log)

included into 1.3.1-stable.0

### LINKED ISSUE #1407: IMA frames stop work after some time
Preconditions:
IMA: 1.1.3-beta.0
Skaled: 3.14.9-stable.1

Description:
After some time in ima agent frames stop working on part of agents

Step to reproduce:
Not have have exec steps right now

Actual result:
After some time ima frames(loop) stop working, as result ima transfers not working properly.

Note: container up and running, our health check not catch this problem. Need to clarify root cause.

### LINKED ISSUE #1453: Improve IMA integration tests
IMA integration tests are running on each pull request and cover most of Solidity and JavaScript code. Unfortunatelly not all the code and much more functions can be covered. We need add more small per-function and per-feature tests.

### LINKED ISSUE #1467: Speed-up SNB with Multi-call
**SKALE Network Browser** part of **IMA Agent** does a lot of read-only `eth_call`-s. These calls can be optimized by packing them into multi-calls using already deployed contract known as `Multicall3` and corresponding interaction components:
- https://wagmi.sh/core/actions/multicall
- https://www.npmjs.com/package/ethereum-multicall

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/IMA/issues/1413
- [ ] https://github.com/skalenetwork/internal-support/issues/569
- [ ] https://github.com/skalenetwork/IMA/issues/1531
```

### LINKED ISSUE #1468: Use comprehensive tests in CI
Need to integrate https://github.com/skalenetwork/comprehensive-test in the test pipeline:
- [ ] Create a separate workflow (or use old one) to clone and run tests for IMA agent
- [ ] Run this workflow for v-branches and develop branches after new merge into them
- [ ] Make passing this tests required to merge v-branch into develop and develop into beta

### LINKED ISSUE #1478: Refactor source code of IMA Agent to follow Code Guidelines
Refactor source code of **IMA Agent** to follow **Code Guidelines** https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md

### PR DESCRIPTION
**Pull request by sergiy-skalelabs**
- **IMA Agent** was re-written 90% from scratch and now based on **ethers.js**
- All **JavaScript** code is ES6 now, so all files are `*.mjs`
- Fixed OKR requirements, all JS lines of code are limited to `100` characters, all JS functions are limited to `200` lines of code including empty lines, everything named `camelCase` everywhere it was possible, massive source code cleanup
- Fixed documentation missmprints and errors, updated documentation with descriptions of changed command line options
- Fixed PY tests run issues on fast local computers
- Fixed JS tests errors running on local computers
- Cleaned up docker file and github action scripts
- Improved **IMA Agent** logging filters, all logging messages correspond to appropriate `--verbose=0..9` level
- Fixed all codacy issues and warnings, codacy report is completely clean green now

### CODE REVIEW

File: agent/bls.mjs [hunk 1]
```diff
@@ -195,13 +200,13 @@ function keccak256_message( jarrMessages, nIdxCurrentMsgBlockStart, strFromChain
         // bytesData = imaUtils.bytesAlignLeftWithZeroes( bytesData, 32 );
         // bytesData = imaUtils.invertArrayItemsLR( bytesData ); // do not invert byte order data field (see SKALE-3554 for details)
         arrBytes = imaUtils.bytesConcat( arrBytes, bytesData );
-        // console.log( "3 ---------------", "0x" + imaUtils.bytesToHex( arrBytes, false ) );
+        // console.log( "3 ---------------", owaspUtils.ensure_starts_with_0x( imaUtils.bytesToHex( arrBytes, false ) ) );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 2]
```diff
@@ -221,15 +226,15 @@ function keccak256_message( jarrMessages, nIdxCurrentMsgBlockStart, strFromChain
 
 // const strHashComputed = keccak256_message( [
 //     {
-//         sender: "0xAe79233541427BC70Bd3Bfe452ca4B1c69d5a82e",
-//         destinationContract: "0xd2AaA00400000000000000000000000000000000",
-//         data: "0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000007aa5e36aa15e93d10f4f26357c30f052dacdde5f00000000000000000000000000000000000000000000006c6b935b8bbd400000"
+//         "sender": "0xAe79233541427BC70Bd3Bfe452ca4B1c69d5a82e",
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 3]
```diff
@@ -248,6 +253,35 @@ function keccak256_u256( u256, isHash ) {
     return strMessageHash;
 }
 
+export function keccak256_pwa( nNodeNumber, strLoopWorkType, isStart, ts ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please use the same name conventions across the module, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 4]
```diff
@@ -248,6 +253,35 @@ function keccak256_u256( u256, isHash ) {
...
+    let arrBytes = new Uint8Array();
+    //
+    let bytes_u256 = imaUtils.hexToBytes( nNodeNumber );
+    bytes_u256 = imaUtils.invertArrayItemsLR( bytes_u256 );
+    bytes_u256 = imaUtils.bytesAlignLeftWithZeroes( bytes_u256, 32 );
+    bytes_u256 = imaUtils.invertArrayItemsLR( bytes_u256 );
+    arrBytes = imaUtils.bytesConcat( arrBytes, bytes_u256 );
+    //
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 5]
```diff
@@ -257,16 +291,16 @@ function split_signature_share( signatureShare ) {
...
-    // const strTmpDir = path.resolve( __dirname ) + "/tmp";
     const strTmpDir = "/tmp/ima-bls-glue";
     shell.mkdir( "-p", strTmpDir );
     return strTmpDir;
 }
 
 function alloc_bls_tmp_action_dir() {
     const strActionDir = get_bls_glue_tmp_dir() + "/" + imaUtils.replaceAll( imaUtils.uuid(), "-", "" );
-    shell.mkdir( "-p", strActionDir );
+    // shell.mkdir( "-p", strActionDir );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 6]
```diff
@@ -285,22 +320,22 @@ function perform_bls_glue(
     details.write( strLogPrefix + cc.debug( "Discovered number of BLS participants is " ) + cc.info( nParticipants ) + cc.debug( "." ) + "\n" );
     const strMessageHash = owaspUtils.remove_starting_0x( keccak256_message( jarrMessages, nIdxCurrentMsgBlockStart, strFromChainName ) );
     details.write( strLogPrefix + cc.debug( "Message hash to sign is " ) + cc.info( strMessageHash ) + "\n" );
-    const strPWD = shell.pwd();
+    // const strPWD = shell.pwd();
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 7]
```diff
@@ -285,22 +320,22 @@ function perform_bls_glue(
...
     try {
-        shell.cd( strActionDir );
+        // shell.cd( strActionDir );
         let strInput = "";
         let i = 0; const cnt = arrSignResults.length;
         for( i = 0; i < cnt; ++i ) {
             const jo = arrSignResults[i];
             const strPath = strActionDir + "/sign-result" + jo.index + ".json";
-            details.write( strLogPrefix + cc.normal( "Saving " ) + cc.notice( strPath ) + cc.debug( " file containing " ) + cc.j( jo ) + "\n" );
+            details.write( strLogPrefix + cc.debug( "Saving " ) + cc.notice( strPath ) + cc.debug( " file containing " ) + cc.j( jo ) + "\n" );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Can you provide information about logs? Do we need `cc.debug`, `cc.notice` etc for logs?

File: agent/bls.mjs [hunk 8]
```diff
@@ -538,19 +569,21 @@ function perform_bls_verify_i(
...
     const fnShellRestore = function() {
-        shell.cd( strPWD );
+        // shell.cd( strPWD );
         shell.rm( "-rf", strActionDir );
     };
     let strOutput = "";
     try {
-        shell.cd( strActionDir );
-        const joMsg = { message: keccak256_u256( u256, true ) };
+        // shell.cd( strActionDir );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 9]
```diff
@@ -593,24 +624,25 @@ function perform_bls_verify(
 ) {
     if( !joGlueResult )
         return true;
+    const imaState = state.get();
     const nThreshold = discover_bls_threshold( imaState.joSChainNetworkInfo );
     const nParticipants = discover_bls_participants( imaState.joSChainNetworkInfo );
-    const strPWD = shell.pwd();
+    // const strPWD = shell.pwd();
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please remove commented lines of code, according to guidelines: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 10]
```diff
@@ -374,6 +407,7 @@ function perform_bls_glue(
 }
 
 function perform_bls_glue_u256( details, u256, arrSignResults ) {
+    const imaState = state.get();
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:435]: Please, modify duplicated code of `perform_bls_glue_u256` and `perform_bls_glue`, according to https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 11]
```diff
@@ -482,25 +514,26 @@ function perform_bls_verify_i(
...
+        // shell.cd( strPWD );
         shell.rm( "-rf", strActionDir );
     };
     let strOutput = "";
     try {
-        shell.cd( strActionDir );
+        // shell.cd( strActionDir );
         details.write( strLogPrefix + cc.debug( "BLS node " ) + cc.notice( "#" ) + cc.info( nZeroBasedNodeIndex ) + cc.debug( " - first message nonce is " ) + cc.info( nIdxCurrentMsgBlockStart ) + "\n" );
         details.write( strLogPrefix + cc.debug( "BLS node " ) + cc.notice( "#" ) + cc.info( nZeroBasedNodeIndex ) + cc.debug( " - first source chain name is " ) + cc.info( strFromChainName ) + "\n" );
         details.write( strLogPrefix + cc.debug( "BLS node " ) + cc.notice( "#" ) + cc.info( nZeroBasedNodeIndex ) + cc.debug( " - messages array " ) + cc.j( jarrMessages ) + "\n" );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please, modify duplicated code of perform_bls_verify_i and perform_bls_verify_i_u256, according to https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 12]
```diff
@@ -686,59 +717,70 @@ function perform_bls_verify_u256( details, joGlueResult, u256, joCommonPublicKey
...
-        joAccount = imaState.joAccount_s_chain;
+        joAccount = imaState.chainProperties.sc.joAccount;
         joChainName = joExtraSignOpts.chain_id_dst;
+        const ethersProvider =
+            ( "ethersProvider_src" in joExtraSignOpts && joExtraSignOpts.ethersProvider_src )
+                ? joExtraSignOpts.ethersProvider_src
+                : null
+                ;
+        if( ! ethersProvider )
+            throw new Error( "CRITICAL ERROR: No provider specified in extra signing options for checking messages of direction \"" + strDirection + "\"" );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#code-line-length

File: agent/bls.mjs [hunk 13]
```diff
@@ -748,30 +790,34 @@ async function check_correctness_of_messages_to_sign( details, strLogPrefix, str
...
-                    cc.debug( ", real message index is: " ) + cc.info( idxMessage ) +
-                    cc.debug( ", saved msgCounter is: " ) + cc.info( outgoingMessageData.msgCounter ) +
-                    "\n" );
-                const m = joMessageProxy.methods.verifyOutgoingMessageData(
-                    outgoingMessageData
+                // details.write(
+                //     cc.debug( "Outgoing message data is " ) + cc.j( outgoingMessageData ) +
+                //     cc.debug( ", real message index is: " ) + cc.info( idxMessage ) +
+                //     cc.debug( ", saved msgCounter is: " ) + cc.info( outgoingMessageData.msgCounter ) +
+                //     "\n" );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 14]
```diff
@@ -810,8 +857,14 @@ async function do_sign_messages_impl(
     joExtraSignOpts,
     fn
 ) {
+    const imaState = state.get();
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please, modify function so its maximum size will be 100 codelines:
https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 15]
```diff
@@ -1334,9 +1400,9 @@ async function do_sign_messages_s2s(
     );
 }
 
-async function do_sign_u256( u256, details, fn ) {
+export async function do_sign_u256( u256, details, fn ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please, modify function so its maximum size will be 100 codelines:
https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 16]
```diff
@@ -1623,14 +1693,498 @@ async function do_sign_u256( u256, details, fn ) {
...
+        details.write( strErrorMessage );
+    }
+    const isSuccess = ( joSignResult && typeof joSignResult == "object" && ( !joSignResult.error ) ) ? true : false;
+    if( isExposeOutput || ( !isSuccess ) )
+        details.exposeDetailsTo( log, "BLS-raw-signer", isSuccess );
+    details.close();
+    return joSignResult;
+}
+
+export async function handle_skale_imaVerifyAndSign( joCallData ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please, modify function so its maximum size will be 100 codelines:
https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 17]
```diff
@@ -1623,14 +1693,498 @@ async function do_sign_u256( u256, details, fn ) {
...
+            "\n";
+        log.write( strErrorMessage );
+        details.write( strErrorMessage );
+    }
+    details.exposeDetailsTo( log, "IMA messages verifier/signer", isSuccess );
+    details.close();
+    return joRetVal;
+}
+
+export async function handle_skale_imaBSU256( joCallData ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Please, modify function so its maximum size will be 100 codelines:
https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
Please modify the modules, according guidelines:
- https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length
- https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#code-line-length
- https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code
- https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#redundancy
- https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs (hunk 3 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Removed

File: agent/bls.mjs (hunk 1 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: removed

File: agent/bls.mjs (hunk 4 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: removed

File: agent/bls.mjs (hunk 5 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: removed

File: agent/bls.mjs (hunk 13 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: removed

File: agent/bls.mjs (hunk 3 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 14 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 15 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 17 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 16 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 6 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 8 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 9 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done

File: agent/bls.mjs (hunk 10 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:435]: Done

File: agent/bls.mjs (hunk 11 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done. it was split into different parts

File: agent/bls.mjs (hunk 12 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done, code line length check also added into ES-LINT settings and done for all JS code now

File: agent/bls.mjs (hunk 7 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: `cc` means `Console Colors`. We use coloring in logs. We need it.

File: .github/workflows/comprehensive.yml [hunk 18]
```diff
@@ -0,0 +1,487 @@
...
+        cat /etc/os-release || true
+        echo ------------ /proc/version
+        cat /proc/version || true
+        echo ------------ lscpu
+        lscpu || true
+
+    - name: UPDATE - system deps and install libc6, net-tools, btrfs-progs, zip, unzip, bash, procps
+      run: |
+        sudo apt-get update
+        #sudo apt-get upgrade
```
Comment (DmytroNazarenko) [inline .github/workflows/comprehensive.yml]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: .github/workflows/comprehensive.yml [hunk 19]
```diff
@@ -0,0 +1,487 @@
...
+    - name: INIT - install Ethereum Main Net emulation
+      working-directory: ${{env.working-directory}}
+      run: |
+        cd comprehensive-test
+        pwd
+        #
+        # # --- ganache-cli version ---
+        # sudo yarn global add ganache-cli
+        # which ganache-cli
+        # ganache-cli --version
```
Comment (DmytroNazarenko) [inline .github/workflows/comprehensive.yml]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: .github/workflows/comprehensive.yml [hunk 20]
```diff
@@ -0,0 +1,487 @@
...
+        cd ..
+
+    - name: INIT - startup Ethereum Main Net emulation
+      working-directory: ${{env.working-directory}}
+      run: |
+        cd comprehensive-test
+        #
+        # # --- ganache-cli version ---
+        # cd cli-ganache
+        # ./run.sh &> ../local_mainnet_output_log.txt &
```
Comment (DmytroNazarenko) [inline .github/workflows/comprehensive.yml]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: .github/workflows/comprehensive.yml [hunk 21]
```diff
@@ -0,0 +1,487 @@
...
+        # cd ..
+        #
+        # # --- hardhat version ---
+        cd cli-hh
+        ./run.sh &> ../local_mainnet_output_log.txt &
+        cd ..
+        #
```
Comment (DmytroNazarenko) [inline .github/workflows/comprehensive.yml]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: .github/workflows/comprehensive.yml [hunk 22]
```diff
@@ -0,0 +1,487 @@
...
+        # - name: INIT - start S-Chain node 01
+        #   run: |
+        #     cd s_chain_gen/node_01
+        #     # ./run-skaled.sh &>/dev/null &
+        #     ./run-skaled.sh &> ./log_skaled_01.txt &
+        #     sleep 30
+        #     cat ./log_skaled_01.txt
+        #     cd ../..
+        #
```
Comment (DmytroNazarenko) [inline .github/workflows/comprehensive.yml]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: .eslintrc.js [hunk 23]
```diff
@@ -60,6 +60,10 @@ module.exports = {
         "no-use-before-define": "off", // [ "error", { "variables": false,  "functions": false } ],
         "lines-between-class-members": [ "error", "never" ],
         "no-var": "error",
-        "no-unused-vars": "error"
+        "no-unused-vars": "error",
+        "object-shorthand": 0,
+        "multiline-ternary": "off",
+        "max-len": [ "error", { "code": 100, "tabWidth": 4 } ],
+        "max-lines-per-function": [ "error", { "max": 200, "skipBlankLines": false } ]
```
Comment (DmytroNazarenko) [inline .eslintrc.js:67]: According to guidelines it is reasonable to set max lines per func = 100: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: .github/workflows/main.yml [hunk 24]
```diff
@@ -350,7 +350,8 @@ jobs:
     - name: Start background ganache
       run: |
         cd proxy
-        NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 12000000 --quiet --allowUnlimitedContractSize --acctKeys ../test/accounts.json &
+        #NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 12000000 --quiet --allowUnlimitedContractSize --acctKeys ../test/accounts.json &
```
Comment (DmytroNazarenko) [inline .github/workflows/main.yml]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: Dockerfile [hunk 25]
```diff
@@ -1,7 +1,20 @@
-FROM node:16
+FROM ubuntu:jammy
 
 RUN apt-get update
-RUN apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
+RUN apt-get install -yq software-properties-common
+RUN apt-get update
+#RUN apt-get upgrade
```
Comment (DmytroNazarenko) [inline Dockerfile]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 26]
```diff
@@ -0,0 +1,2976 @@
...
+
+function alloc_bls_tmp_action_dir() {
+    const strActionDir =
+        get_bls_glue_tmp_dir() + "/" + imaUtils.replaceAll( imaUtils.uuid(), "-", "" );
+    if( ! fs.existsSync( strActionDir ) )
+        fs.mkdirSync( strActionDir , { recursive: true } );
+    return strActionDir;
+}
+
+function perform_bls_glue(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 27]
```diff
@@ -0,0 +1,2976 @@
...
+            "\n";
+        details.write( s1 );
+        details.write( s2 );
+        fnShellRestore();
+        joGlueResult = null;
+    }
+    return joGlueResult;
+}
+
+function perform_bls_glue_u256( details, u256, arrSignResults ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 28]
```diff
@@ -0,0 +1,2976 @@
...
+            cc.notice( strOutput ) +
+            "\n";
+        details.write( s1 );
+        details.write( s2 );
+        fnShellRestore();
+    }
+    return false;
+}
+
+async function check_correctness_of_messages_to_sign(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 29]
```diff
@@ -0,0 +1,2976 @@
...
+    optsSignOperation.details.write( optsSignOperation.strLogPrefix +
+        cc.debug( "Will collect " ) + cc.info( optsSignOperation.nCountOfBlsPartsToCollect ) +
+        cc.debug( " from " ) + cc.info( optsSignOperation.jarrNodes.length ) +
+        cc.debug( " nodes" ) +
+        cc.debug( ", " ) + cc.notice( "sequence ID" ) + cc.debug( " is " ) +
+        cc.attention( optsSignOperation.sequence_id ) +
+        "\n" );
+}
+
+async function gather_signing_start_impl( optsSignOperation ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 30]
```diff
@@ -0,0 +1,2976 @@
...
+        await joCall.disconnect();
+        throw new Error(
+            "CRITICAL ERROR: " +
+            "Failed do_sign_messages_impl() with unknown direction \"" +
+            optsSignOperation.strDirection + "\""
+        );
+    }
+}
+
+async function do_sign_process_handle_call(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 31]
```diff
@@ -0,0 +1,2976 @@
...
+            await do_sign_process_handle_call(
+                optsSignOperation,
+                joNode, joParams,
+                joIn, joOut, err
+            );
+        } ); // joCall.call ...
+    } ); // rpcCall.create ...
+}
+
+async function do_sign_messages_impl(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 32]
```diff
@@ -0,0 +1,2976 @@
...
+    }
+    optsSign_u256.nCountOfBlsPartsToCollect = 0 + optsSign_u256.nThreshold;
+    optsSign_u256.details.write( optsSign_u256.strLogPrefix +
+        cc.debug( "Will(optsSign_u256.u256) collect " ) +
+        cc.info( optsSign_u256.nCountOfBlsPartsToCollect ) +
+        cc.debug( " from " ) + cc.info( optsSign_u256.jarrNodes.length ) + cc.debug( " nodes" ) +
+        "\n" );
+}
+
+async function do_sign_u256_one_impl( optsSign_u256 ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 33]
```diff
@@ -0,0 +1,2976 @@
...
+        fnShellRestore();
+        isSuccess = false;
+    }
+    if( isExposeOutput || ( !isSuccess ) )
+        details.exposeDetailsTo( log, "BLS-raw-verifier", isSuccess );
+    details.close();
+    return isSuccess;
+}
+
+export async function do_sign_ready_hash( strMessageHash, isExposeOutput ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 34]
```diff
@@ -0,0 +1,2976 @@
...
+        skale_observer: skale_observer,
+        ethersProvider_src: owaspUtils.getEthersProviderFromURL( strUrlSrcSChain ),
+        chain_id_src: optsHandleVerifyAndSign.strFromChainName,
+        chain_id_dst: optsHandleVerifyAndSign.strToChainName,
+        cid_src: optsHandleVerifyAndSign.strFromChainID,
+        cid_dst: optsHandleVerifyAndSign.strToChainID
+    };
+}
+
+export async function handle_skale_imaVerifyAndSign( joCallData ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 35]
```diff
@@ -0,0 +1,2976 @@
...
+    if( ! optsBSU256.joAccount.strURL ) {
+        optsBSU256.joAccount = optsBSU256.imaState.chainProperties.mn.optsBSU256.joAccount;
+        if( ! optsBSU256.joAccount.strSgxURL )
+            throw new Error( "SGX URL is unknown, cannot sign U256" );
+        if( ! optsBSU256.joAccount.strBlsKeyName )
+            throw new Error( "BLS keys name is unknown, cannot sign U256" );
+    }
+}
+
+export async function handle_skale_imaBSU256( joCallData ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#function-length

File: agent/bls.mjs [hunk 36]
```diff
@@ -0,0 +1,2976 @@
...
+import { randomCallID } from "../npms/skale-cool-socket/socket_utils.mjs";
+
+const shell = shell_mod.default;
+
+const Keccak = sha3_mod.Keccak;
+
+const sleep =
+    ( milliseconds ) => { return new Promise( resolve => setTimeout( resolve, milliseconds ) ); };
+
+const g_secondsMessageVerifySendTimeout = 2 * 60;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 37]
```diff
@@ -0,0 +1,2976 @@
...
+
+async function with_timeout( strDescription, promise, seconds ) {
+    strDescription = strDescription || "with_timeout()";
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 38]
```diff
@@ -0,0 +1,2976 @@
...
+    let result_err = null, isComplete = false;
+    promise.catch( function( err ) {
+        isComplete = true;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:53]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 39]
```diff
@@ -0,0 +1,2976 @@
...
+        result_err =
+            new Error( strDescription + "error: " + owaspUtils.extract_error_message( err ) );
+    } ).finally( function() {
+        isComplete = true;
+    } );
+    for( let idxWaitStep = 0; idxWaitStep < seconds; ++ idxWaitStep ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:59]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 40]
```diff
@@ -0,0 +1,2976 @@
...
+    }
+    if( result_err )
+        throw result_err;
+    if( ! isComplete )
+        throw new Error( strDescription + " reached limit of " + seconds + " second(s)" );
+};
+
+function discover_bls_threshold( joSChainNetworkInfo ) {
+    const imaState = state.get();
+    joSChainNetworkInfo = joSChainNetworkInfo || imaState.joSChainNetworkInfo;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:72]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#coherent-style

File: agent/bls.mjs [hunk 41]
```diff
@@ -0,0 +1,2976 @@
...
+    arrBytes = imaUtils.bytesConcat(
+        arrBytes,
+        hexPrepare(
+            owaspUtils.ensure_starts_with_0x( nIdxCurrentMsgBlockStart.toString( 16 ) ),
+            false,
+            false
+        )
+    );
+    arrBytes = a2ha( arrBytes );
+    let i = 0; const cnt = jarrMessages.length;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Redundant i=0

File: agent/bls.mjs [hunk 42]
```diff
@@ -0,0 +1,2976 @@
...
+        cc.debug( " director with " ) + cc.info( arrSignResults.length ) +
+        cc.debug( " sign results..." ) +
+        "\n" );
+    const fnShellRestore = function() {
+        shell.rm( "-rf", strActionDir );
+    };
+    let strOutput = "";
+    try {
+        let strInput = "";
+        let i = 0; const cnt = arrSignResults.length;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Redundant i=0

File: agent/bls.mjs [hunk 43]
```diff
@@ -0,0 +1,2976 @@
...
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Redundant i=0

File: agent/bls.mjs [hunk 44]
```diff
@@ -0,0 +1,2976 @@
...
+            const joCallSGX = {
+                "jsonrpc": "2.0",
+                "id": randomCallID(),
+                "method": "blsSignMessageHash",
+                "params": {
+                    "keyShareName": joAccount.strBlsKeyName,
+                    "messageHash": strMessageHash,
+                    "n": nParticipants,
+                    "t": nThreshold,
+                    "signerIndex": signerIndex + 0 // 1-based
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:2561]: Could be replaced by `"signerIndex": signerIndex`

File: agent/bls.mjs [hunk 45]
```diff
@@ -0,0 +1,2976 @@
...
+            const joCallSGX = {
+                "jsonrpc": "2.0",
+                "id": randomCallID(),
+                "method": "blsSignMessageHash",
+                "params": {
+                    "keyShareName": joAccount.strBlsKeyName,
+                    "messageHash": optsHandleVerifyAndSign.strMessageHash,
+                    "n": optsHandleVerifyAndSign.nParticipants,
+                    "t": optsHandleVerifyAndSign.nThreshold,
+                    "signerIndex": signerIndex + 0 // 1-based
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:2851]: Could be replaced by `"signerIndex": signerIndex`

File: agent/bls.mjs [hunk 46]
```diff
@@ -0,0 +1,2976 @@
...
+                const joCallSGX = {
+                    "jsonrpc": "2.0",
+                    "id": randomCallID(),
+                    "method": "blsSignMessageHash",
+                    "params": {
+                        "keyShareName": optsBSU256.joAccount.strBlsKeyName,
+                        "messageHash": optsBSU256.strMessageHash,
+                        "n": optsBSU256.nParticipants,
+                        "t": optsBSU256.nThreshold,
+                        "signerIndex": signerIndex + 0 // 1-based
```
Comment (DmytroNazarenko) [inline agent/bls.mjs:3046]: Could be replaced by `"signerIndex": signerIndex`

File: agent/bls.mjs [hunk 47]
```diff
@@ -0,0 +1,2976 @@
...
+
+    let jo_schain_src = null, strUrlSrcSChain = null;
+    for( let idxSChain = 0; idxSChain < arr_schains_cached.length; ++ idxSChain ) {
+        const jo_schain = arr_schains_cached[idxSChain];
+        if( jo_schain.data.name.toString() == strSChainNameSrc.toString() ) {
+            jo_schain_src = jo_schain;
+            strUrlSrcSChain = skale_observer.pick_random_schain_url( jo_schain );
+            break;
+        }
+    } // for( let idxSChain = 0; idxSChain < arr_schains_cached.length; ++ idxSChain )
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 48]
```diff
@@ -0,0 +1,2976 @@
...
+                    cc.debug( "Stop invoking " ) + cc.info( "skale_imaVerifyAndSign" ) +
+                    cc.debug( " for transfer from chain " ) + cc.info( fromChainName ) +
+                    cc.debug( " at #" ) + cc.info( i ) +
+                    cc.debug( " because successfully gathered count is reached " ) +
+                    cc.j( optsSignOperation.cntSuccess ) +
+                    "\n" );
+                break;
+            }
+            await do_sign_process_one_impl( i, optsSignOperation );
+        } // for( let i = 0; i < optsSignOperation.jarrNodes.length; ++i )
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 49]
```diff
@@ -0,0 +1,2976 @@
...
+                    log.write( strErrorMessage );
+                }
+                const strCallbackCallDescription =
+                    cc.debug( "Will call signed-hash answer-sending callback " ) +
+                    ( strError ? ( cc.debug( " with error " ) + cc.j( strError ) ) : "" ) +
+                    cc.debug( ", optsSignOperation.jarrMessages is " ) +
+                    cc.j( optsSignOperation.jarrMessages ) +
+                    cc.debug( ", glue result is " ) + cc.j( joGlueResult ) + "\n";
+                optsSignOperation.details.write( strCallbackCallDescription );
+                /*await*/ optsSignOperation.fn(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 50]
```diff
@@ -0,0 +1,2976 @@
...
+                    optsSignOperation.errGathering = strError;
+                    reject( new Error( optsSignOperation.errGathering ) );
+                } else
+                    resolve();
+                return;
+            }
+            if( optsSignOperation.joGatheringTracker.nCountReceived >=
+                    optsSignOperation.jarrNodes.length ) {
+                clearInterval( iv );
+                /*await*/ optsSignOperation.fn(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 51]
```diff
@@ -0,0 +1,2976 @@
...
+                    reject( new Error( optsSignOperation.errGathering ) );
+                } );
+                optsSignOperation.bHaveResultReportCalled = true;
+                return;
+            }
+            if( optsSignOperation.joGatheringTracker.nWaitIntervalStepsDone >=
+                    optsSignOperation.joGatheringTracker.nWaitIntervalMaxSteps
+            ) {
+                clearInterval( iv );
+                /*await*/ optsSignOperation.fn(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 52]
```diff
@@ -0,0 +1,2976 @@
...
+        ? imaUtils.compose_ima_agent_node_url( joNode )
+        : imaUtils.compose_schain_node_url( joNode );
+    const strNodeDescColorized = cc.u( strNodeURL ) + " " +
+        cc.debug( "(" ) + cc.bright( i ) + cc.debug( "/" ) +
+        cc.bright( optsSignOperation.jarrNodes.length ) +
+        cc.debug( ", ID " ) + cc.info( joNode.nodeID ) + cc.debug( ")" ) +
+        cc.debug( ", " ) + cc.notice( "sequence ID" ) + cc.debug( " is " ) +
+        cc.attention( optsSignOperation.sequence_id );
+    const rpcCallOpts = null;
+    /*await*/ rpcCall.create( strNodeURL, rpcCallOpts, async function( joCall, err ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

File: agent/bls.mjs [hunk 53]
```diff
@@ -0,0 +1,2976 @@
...
+        nParticipants: 1,
+        nCountOfBlsPartsToCollect: 1,
+        errGathering: null,
+        promise_gathering_complete: null
+    };
+    optsSign_u256.jarrNodes = optsSign_u256.imaState.joSChainNetworkInfo.network;
+    optsSign_u256.details.write( optsSign_u256.strLogPrefix +
+        cc.debug( "Invoking signing u256 procedure " ) + "\n" );
+    optsSign_u256.fn = optsSign_u256.fn || function() {};
+    if( !( /*optsSign_u256.imaState.bSignMessages &&*/
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md#commented-out-code

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
According guidelines https://github.com/skalenetwork/internal-support/blob/main/docs/wiki/code-guidelines.md:
- Need to use only snake_case style (or only camelCase) for all functions and vars
- Max function size should be <= 100 lines of code
- Remove redundant comments from all files

File: .github/workflows/comprehensive.yml (hunk 19 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml]: Fixed

File: .github/workflows/comprehensive.yml (hunk 21 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml]: Fixed

File: .github/workflows/comprehensive.yml (hunk 22 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml]: Fixed

File: agent/bls.mjs (hunk 53 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 51 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 52 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 50 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: .github/workflows/comprehensive.yml (hunk 20 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml]: Fixed

File: agent/bls.mjs (hunk 49 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: .github/workflows/comprehensive.yml (hunk 18 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml]: Fixed

File: .eslintrc.js (hunk 23 above)
Comment (sergiy-skalelabs) [reply .eslintrc.js:67]: We have 200 again))

File: .github/workflows/main.yml (hunk 24 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Fixed

File: Dockerfile (hunk 25 above)
Comment (sergiy-skalelabs) [reply Dockerfile]: Fixed

File: agent/bls.mjs (hunk 27 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 28 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 26 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 29 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 30 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 31 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 32 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 33 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 34 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 35 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 36 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed, but `g_` prefixes are left for globals

File: agent/bls.mjs (hunk 38 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:53]: Fixed

File: agent/bls.mjs (hunk 40 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:72]: Fixed

File: agent/bls.mjs (hunk 39 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:59]: Fixed

File: agent/bls.mjs (hunk 41 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 42 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 43 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 44 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:2561]: No, `+0` here is trick for creating copy of value instead of variable reference))

File: agent/bls.mjs (hunk 46 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:3046]: This is trick for creating copy of value

File: agent/bls.mjs (hunk 45 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs:2851]: This is trick for creating copy of value

File: agent/bls.mjs (hunk 47 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 48 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: Dockerfile (hunk 25 above)
Comment (DmytroNazarenko) [reply Dockerfile]: Still valid

File: agent/bls.mjs [hunk 54]
```diff
@@ -0,0 +1,2987 @@
...
+ * @copyright SKALE Labs 2019-Present
+ */
+
+import * as fs from "fs";
+import * as cc from "../npms/skale-cc/cc.mjs";
+import * as log from "../npms/skale-log/log.mjs";
+import * as owaspUtils from "../npms/skale-owasp/owasp-utils.mjs";
+import * as child_process from "child_process";
+import * as rpcCall from "./rpc-call.mjs";
+import * as shell_mod from "shelljs";
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch modules to camelCase, please

File: agent/bls.mjs [hunk 55]
```diff
@@ -0,0 +1,2987 @@
...
+import * as imaUtils from "./utils.mjs";
+import * as sha3_mod from "sha3";
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch modules to camelCase, please

File: agent/bls.mjs [hunk 56]
```diff
@@ -0,0 +1,2987 @@
...
+    ( milliseconds ) => { return new Promise( resolve => setTimeout( resolve, milliseconds ) ); };
+
+const g_secondsMessageVerifySendTimeout = 2 * 60;
+
+async function withTimeout( strDescription, promise, seconds ) {
+    strDescription = strDescription || "withTimeout()";
+    let result_err = null, isComplete = false;
+    promise.catch( function( err ) {
+        isComplete = true;
+        result_err =
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 57]
```diff
@@ -0,0 +1,2987 @@
...
+    if( isInvertBefore )
+        arrBytes = imaUtils.invertArrayItemsLR( arrBytes );
+    arrBytes = imaUtils.bytesAlignLeftWithZeroes( arrBytes, 32 );
+    if( isInvertAfter )
+        arrBytes = imaUtils.invertArrayItemsLR( arrBytes );
+    return arrBytes;
+}
+
+function s2ha( s ) {
+    const str_u256 = owaspUtils.ethersMod.ethers.utils.id( s );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 58]
```diff
@@ -0,0 +1,2987 @@
...
+        arrBytes = imaUtils.bytesConcat( arrBytes, bytesData );
+        arrBytes = a2ha( arrBytes );
+    }
+    return owaspUtils.ensureStartsWith0x( imaUtils.bytesToHex( arrBytes, false ) );
+}
+
+export function keccak256_u256( u256, isHash ) {
+    let arrBytes = new Uint8Array();
+
+    let bytes_u256 = imaUtils.hexToBytes( u256 );
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 59]
```diff
@@ -0,0 +1,2987 @@
...
+    if( isHash ) {
+        const hash = new Keccak( 256 );
+        hash.update( imaUtils.toBuffer( arrBytes ) );
+        strMessageHash = hash.digest( "hex" );
+    } else
+        strMessageHash = "0x" + imaUtils.bytesToHex( arrBytes );
+    return strMessageHash;
+}
+
+export function keccak256_4_pending_work_analysis( nNodeNumber, strLoopWorkType, isStart, ts ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 60]
```diff
@@ -0,0 +1,2987 @@
...
+}
+
+function a2ha( arrBytes ) {
+    const k = new Keccak( 256 );
+    k.update( imaUtils.toBuffer( arrBytes ) );
+    const h = k.digest( "hex" );
+    return imaUtils.hexToBytes( "0x" + h );
+}
+
+function keccak256_message( jarrMessages, nIdxCurrentMsgBlockStart, strFromChainName ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 61]
```diff
@@ -0,0 +1,2987 @@
...
+        const joMsg = { "message": strMessageHash };
+        details.write( strLogPrefix +
+            cc.debug( "BLS/summary verify message - composed JSON " ) + cc.j( joMsg ) +
+            cc.debug( " from messages array " ) + cc.j( jarrMessages ) +
+            cc.debug( " using glue " ) + cc.j( joGlueResult ) +
+            cc.debug( " and common public key " ) + cc.j( joCommonPublicKey ) +
+            "\n" );
+        imaUtils.jsonFileSave( strActionDir + "/glue-result.json", joGlueResult );
+        imaUtils.jsonFileSave( strActionDir + "/hash.json", joMsg );
+        const joCommonPublicKey_for_O = {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 62]
```diff
@@ -0,0 +1,2987 @@
...
+    strLogPrefix,
+    strDirection,
+    jarrMessages,
+    nIdxCurrentMsgBlockStart,
+    joExtraSignOpts
+) {
+    const imaState = state.get();
+    let joMessageProxy = null, joAccount = null, joChainName = null;
+    if( strDirection == "M2S" ) {
+        joMessageProxy = imaState.jo_message_proxy_main_net;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 63]
```diff
@@ -0,0 +1,2987 @@
...
+        joAccount = imaState.chainProperties.mn.joAccount;
+        joChainName = imaState.chainProperties.sc.strChainName;
+    } else if( strDirection == "S2M" ) {
+        joMessageProxy = imaState.jo_message_proxy_s_chain;
+        joAccount = imaState.chainProperties.sc.joAccount;
+        joChainName = imaState.chainProperties.mn.strChainName;
+    } else if( strDirection == "S2S" ) {
+        joAccount = imaState.chainProperties.sc.joAccount;
+        joChainName = joExtraSignOpts.chain_id_dst;
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 64]
```diff
@@ -0,0 +1,2987 @@
...
+        details.write( strLogPrefix +
+            cc.success( "Correctness validation passed for " ) + cc.info( cnt ) +
+            cc.success( " message(s)" ) +
+            "\n" );
+    }
+}
+
+async function prepareSignMessagesImpl( optsSignOperation ) {
+    optsSignOperation.fn = optsSignOperation.fn || function() {};
+    optsSignOperation.sequence_id =
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 65]
```diff
@@ -0,0 +1,2987 @@
...
+        cc.debug( ", " ) + cc.notice( "sequence ID" ) + cc.debug( " is " ) +
+        cc.attention( optsSignOperation.sequence_id ) +
+        "\n" );
+}
+
+async function gatherSigningStartImpl( optsSignOperation ) {
+    optsSignOperation.details.write( optsSignOperation.strLogPrefix +
+        cc.debug( "Waiting for BLS glue result " ) + "\n" );
+    optsSignOperation.errGathering = null;
+    optsSignOperation.promise_gathering_complete = new Promise( ( resolve, reject ) => {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 66]
```diff
@@ -0,0 +1,2987 @@
...
+            const joParams = {
+                "direction": "" + optsSignOperation.strDirection,
+                "startMessageIdx": optsSignOperation.nIdxCurrentMsgBlockStart,
+                "dstChainName": optsSignOperation.targetChainName,
+                "srcChainName": optsSignOperation.fromChainName,
+                "dstChainID": optsSignOperation.targetChainID,
+                "srcChainID": optsSignOperation.fromChainID,
+                "messages": optsSignOperation.jarrMessages,
+                "qa": {
+                    "skaled_no": 0 + i,
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 67]
```diff
@@ -0,0 +1,2987 @@
...
+        nTransferLoopCounter,
+        "S2S",
+        jarrMessages, nIdxCurrentMsgBlockStart, strFromChainName,
+        joExtraSignOpts,
+        fn
+    );
+}
+
+async function prepareSignU256( optsSign_u256 ) {
+    optsSign_u256.details.write( optsSign_u256.strLogPrefix +
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 68]
```diff
@@ -0,0 +1,2987 @@
...
+                    "\n";
+                log.write( strErrorMessage );
+                optsSign_u256.details.write( strErrorMessage );
+            }
+            await joCall.disconnect();
+        } ); // joCall.call ...
+    } ); // rpcCall.create ...
+}
+
+async function doSignU256Gathering( optsSign_u256 ) {
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 69]
```diff
@@ -0,0 +1,2987 @@
...
+                    "signerIndex": signerIndex + 0 // 1-based
+                }
+            };
+            details.write( strLogPrefix +
+                cc.debug( "Will invoke " ) + cc.info( "SGX" ) +
+                cc.debug( " with call data " ) + cc.j( joCallSGX ) +
+                "\n" );
+            await joCall.call( joCallSGX, async function( joIn, joOut, err ) {
+                if( err ) {
+                    const err_js = new Error(
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/bls.mjs [hunk 70]
```diff
@@ -0,0 +1,2987 @@
...
+async function prepareS2sOfSkaleImaVerifyAndSign( optsHandleVerifyAndSign ) {
+    const strSChainNameSrc = optsHandleVerifyAndSign.joCallData.params.srcChainName;
+    const strSChainNameDst = optsHandleVerifyAndSign.joCallData.params.dstChainName;
+    optsHandleVerifyAndSign.details.write( optsHandleVerifyAndSign.strLogPrefix +
+        cc.bright( optsHandleVerifyAndSign.strDirection ) +
+        cc.debug( " verification algorithm will use for source chain name " ) +
+        cc.info( strSChainNameSrc ) +
+        cc.debug( " and destination chain name " ) + cc.info( strSChainNameDst ) +
+        "\n" );
+    const arr_schains_cached = skaleObserver.getLastCachedSChains();
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Switch to camelCase, please

File: agent/cli.mjs [hunk 71]
```diff
@@ -0,0 +1,4309 @@
...
+        imaState.nAutoExitAfterSeconds = owaspUtils.toInteger( joArg.value );
+        return true;
+    }
+    return false;
+}
+
+export function parse( joExternalHandlers, argv ) {
+    const imaState = state.get();
+    let idxArg; const cntArgs = argv || process.argv.length;
+    for( idxArg = 2; idxArg < cntArgs; ++idxArg ) {
```
Comment (DmytroNazarenko) [inline agent/cli.mjs]: Maybe move def of idxArg to for(...)

File: agent/loop.mjs [hunk 72]
```diff
@@ -0,0 +1,794 @@
...
+
+import * as network_layer from "../npms/skale-cool-socket/socket.mjs";
+import * as url from "url";
+import { Worker } from "worker_threads";
+import * as path from "path";
+import * as cc from "../npms/skale-cc/cc.mjs";
+import * as log from "../npms/skale-log/log.mjs";
+import * as IMA from "../npms/skale-ima/index.mjs";
+import * as owaspUtils from "../npms/skale-owasp/owasp-utils.mjs";
+// import * as imaUtils from "./utils.mjs";
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Remove comments, please

File: agent/loop.mjs [hunk 73]
```diff
@@ -0,0 +1,794 @@
...
+import * as imaBLS from "./bls.mjs";
+import * as skaleObserver from "../npms/skale-observer/observer.mjs";
+// import * as imaOracle from "./oracle.mjs";
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Remove comments, please

File: agent/loop.mjs [hunk 74]
```diff
@@ -0,0 +1,794 @@
...
+import * as pwa from "./pwa.mjs";
+import * as state from "./state.mjs";
+
+const __dirname = path.dirname( url.fileURLToPath( import.meta.url ) );
+
+///////////////////////////////////////////////////////////////////////////////////////////////////
+///////////////////////////////////////////////////////////////////////////////////////////////////
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Mb remove?

File: agent/loop.mjs [hunk 75]
```diff
@@ -0,0 +1,794 @@
...
+                }
+            } else {
+                if( checkTimeFraming( null, "oracle", optsLoop.joRuntimeOpts ) ) {
+                    imaState.loopState.oracle.isInProgress = true;
+                    await pwa.notifyOnLoopStart( imaState, "oracle" );
+                    b0 = IMA.doOracleGasPriceSetup(
+                        imaState.chainProperties.mn.ethersProvider,
+                        imaState.chainProperties.sc.ethersProvider,
+                        imaState.chainProperties.sc.transactionCustomizer,
+                        imaState.jo_community_locker,
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 76]
```diff
@@ -0,0 +1,794 @@
...
+                "\n" );
+        }
+    }
+    return b0;
+}
+
+async function singleTransferLoopPartM2S( optsLoop, strLogPrefix ) {
+    const imaState = state.get();
+    let b1 = true;
+    if( optsLoop.enable_step_m2s ) {
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 77]
```diff
@@ -0,0 +1,794 @@
...
+                        imaState.chainProperties.sc.ethersProvider,
+                        imaState.jo_message_proxy_s_chain,
+
+                        imaState.chainProperties.sc.joAccount,
+                        imaState.chainProperties.mn.strChainName,
+                        imaState.chainProperties.sc.strChainName,
+                        imaState.chainProperties.mn.cid,
+                        imaState.chainProperties.sc.cid,
+                        null,
+                        imaState.jo_token_manager_eth, // for logs validation on s-chain
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 78]
```diff
@@ -0,0 +1,794 @@
...
+    } else
+        await singleTransferLoopWithRepeat( optsLoop );
+    return true;
+}
+
+///////////////////////////////////////////////////////////////////////////////////////////////////
+///////////////////////////////////////////////////////////////////////////////////////////////////
+//
+// Parallel thread based loop
+//
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Maybe move module to separate file?

File: agent/loop.mjs [hunk 79]
```diff
@@ -0,0 +1,794 @@
...
+
+const sleepImpl = ( milliseconds ) => {
+    return new Promise( resolve => setTimeout( resolve, milliseconds ) );
+};
+
+const g_workers = [];
+const g_clients = [];
+
+export function notifyCacheChangedSNB( arr_schains_cached ) {
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 80]
```diff
@@ -0,0 +1,794 @@
...
+        "mn": {
+            "joAccount": {
+                "privateKey":
+                    opts.imaState.chainProperties.mn.joAccount.privateKey,
+                "address_":
+                    opts.imaState.chainProperties.mn.joAccount.address_,
+                "strTransactionManagerURL":
+                    opts.imaState.chainProperties.mn
+                        .joAccount.strTransactionManagerURL,
+                "tm_priority":
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 81]
```diff
@@ -0,0 +1,794 @@
...
+            cc: { isEnabled: cc.isEnabled() }
+        };
+        g_workers.push(
+            new Worker(
+                path.join( __dirname, "loop_worker.mjs" ),
+                { "type": "module", "workerData": workerData }
+            )
+        );
+        g_workers[idxWorker].on( "message", jo => {
+            if( network_layer.out_of_worker_apis.on_message( g_workers[idxWorker], jo ) )
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 82]
```diff
@@ -0,0 +1,794 @@
...
+            joRuntimeOpts: {
+                isInsideWorker: true,
+                idxChainKnownForS2S: 0,
+                cntChainsKnownForS2S: 0
+            },
+            isDelayFirstRun: false,
+            enable_step_oracle: ( idxWorker == 0 ) ? true : false,
+            enable_step_m2s: ( idxWorker == 0 ) ? true : false,
+            enable_step_s2m: ( idxWorker == 1 ) ? true : false,
+            enable_step_s2s: ( idxWorker == 0 ) ? true : false
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 83]
```diff
@@ -0,0 +1,794 @@
...
+                        "jo_token_manager_erc721_with_metadata_target": null,
+                        "jo_community_locker": null,
+                        "jo_community_locker_target": null,
+                        "jo_message_proxy_main_net": null,
+                        "jo_message_proxy_s_chain": null,
+                        "jo_message_proxy_s_chain_target": null,
+                        "jo_token_manager_linker": null,
+                        "jo_token_manager_linker_target": null,
+                        "eth_erc20": null,
+                        "eth_erc20_target": null,
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop.mjs [hunk 84]
```diff
@@ -0,0 +1,794 @@
...
+                        "nReimbursementRange": opts.imaState.nReimbursementRange,
+
+                        "joSChainDiscovery": {
+                            "isSilentReDiscovery":
+                                opts.imaState.joSChainDiscovery.isSilentReDiscovery,
+                            "repeatIntervalMilliseconds":
+                                opts.imaState.joSChainDiscovery.repeatIntervalMilliseconds
+                        },
+
+                        "s2s_opts": { // S-Chain to S-Chain transfer options
```
Comment (DmytroNazarenko) [inline agent/loop.mjs]: Switch to camelCase, please

File: agent/loop_worker.mjs [hunk 85]
```diff
@@ -0,0 +1,212 @@
...
+ * along with SKALE IMA.  If not, see <https://www.gnu.org/licenses/>.
+ */
+
+/**
+ * @file loop_worker.mjs
+ * @copyright SKALE Labs 2019-Present
+ */
+
+import { parentPort, workerData } from "worker_threads";
+import * as network_layer from "../npms/skale-cool-socket/socket.mjs";
```
Comment (DmytroNazarenko) [inline agent/loop_worker.mjs]: Switch to camelCase, please

File: agent/loop_worker.mjs [hunk 86]
```diff
@@ -0,0 +1,212 @@
...
+    const joSend = {
+        "worker_message_type":
+            ( type && typeof type == "string" && type.length > 0 )
+                ? type
+                : "in_worker_message",
+        "worker_endpoint": endpoint,
+        "worker_uuid": worker_uuid,
+        "data": jo
+    };
+    parentPort.postMessage( network_layer.socket_sent_data_marshall( joSend ) );
```
Comment (DmytroNazarenko) [inline agent/loop_worker.mjs]: Switch to camelCase, please

File: agent/main.mjs [hunk 87]
```diff
@@ -0,0 +1,2966 @@
...
+import * as imaBLS from "./bls.mjs";
+import * as pwa from "./pwa.mjs";
+
+import * as state from "./state.mjs";
+
+// allow self-signed wss and https
+process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
+
+///////////////////////////////////////////////////////////////////////////////////////////////////
+///////////////////////////////////////////////////////////////////////////////////////////////////
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Maybe remove?

File: agent/main.mjs [hunk 88]
```diff
@@ -0,0 +1,2966 @@
...
+    const imaState = state.get();
+    imaState.arrActions.push( {
+        "name": "mint ERC721",
+        "fn": async function() {
+            let bMintIsOK = false;
+            if( imaState.chainProperties.tc.strCoinNameErc721.length > 0 ) {
+                try {
+                    const strAddressMintTo = // same as caller/transaction signer
+                        imaState.chainProperties.tc.joAccount.address();
+                    const idTokens = imaState.have_idTokens ? imaState.idTokens : [];
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Switch to camelCase, please

File: agent/main.mjs [hunk 89]
```diff
@@ -0,0 +1,2966 @@
...
+                    imaState.chainProperties.mn.cid,
+                    imaState.chainProperties.sc.cid,
+                    imaState.chainProperties.mn.joAccount,
+                    imaState.chainProperties.sc.joAccount,
+                    imaState.jo_deposit_box_erc20, // only main net
+                    imaState.jo_message_proxy_main_net, // for checking logs
+                    imaState.chainProperties.sc.strChainName,
+                    imaState.nAmountOfToken, // how much ERC20 tokens to send
+                    imaState.nAmountOfWei, // how much to send
+                    imaState.jo_token_manager_erc20, // only s-chain
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Switch to camelCase, please

File: agent/main.mjs [hunk 90]
```diff
@@ -0,0 +1,2966 @@
...
+                    imaState.chainProperties.sc.cid,
+                    imaState.chainProperties.mn.joAccount,
+                    imaState.chainProperties.sc.joAccount,
+                    imaState.jo_deposit_box_erc1155, // only main net
+                    imaState.jo_message_proxy_main_net, // for checking logs
+                    imaState.chainProperties.sc.strChainName,
+                    imaState.idToken, // which ERC1155 token id to send
+                    imaState.nAmountOfToken, // which ERC1155 token amount to send
+                    imaState.nAmountOfWei, // how much to send
+                    imaState.jo_token_manager_erc1155, // only s-chain
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Switch to camelCase, please

File: agent/main.mjs
Comment (DmytroNazarenko) [inline agent/main.mjs:1]: Is it possible to split this file into separate different files to avoid 3k lines in file?

File: agent/main.mjs [hunk 91]
```diff
@@ -0,0 +1,2966 @@
...
+        tmp_address_MN_from_env.length > 0 )
+        imaState.chainProperties.mn.joAccount.address_ = "" + tmp_address_MN_from_env;
+    if( tmp_address_SC_from_env &&
+        typeof tmp_address_SC_from_env == "string" &&
+        tmp_address_SC_from_env.length > 0 )
+        imaState.chainProperties.sc.joAccount.address_ = "" + tmp_address_SC_from_env;
+    if( tmp_address_TC_from_env &&
+        typeof tmp_address_TC_from_env == "string" &&
+        tmp_address_TC_from_env.length > 0 )
+        imaState.chainProperties.tc.joAccount.address_ = "" + tmp_address_TC_from_env;
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Switch to camelCase, please

File: agent/main.mjs [hunk 92]
```diff
@@ -0,0 +1,2966 @@
...
+        }
+    } else
+        doTheJob();
+        // FINISH!!! (skip exit here to avoid early termination while tasks ase still running)
+}
+
+main();
+
+///////////////////////////////////////////////////////////////////////////////////////////////////
+///////////////////////////////////////////////////////////////////////////////////////////////////
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Remove redundant comment, please

File: agent/oracle.mjs [hunk 93]
```diff
@@ -0,0 +1,303 @@
...
+
+/**
+ * @file oracle.mjs
+ * @copyright SKALE Labs 2019-Present
+ */
+
+import * as rpcCall from "./rpc-call.mjs";
+import numberToBN from "number-to-bn";
+
+import * as sha3_mod from "sha3";
```
Comment (DmytroNazarenko) [inline agent/oracle.mjs]: Switch to camelCase, please

File: agent/oracle.mjs [hunk 94]
```diff
@@ -0,0 +1,303 @@
...
+            }
+            break;
+        }
+    }
+    return s;
+}
+
+export function oracleGetGasPrice( oracleOpts, details ) {
+    details = details || log;
+    const promise_complete = new Promise( ( resolve, reject ) => {
```
Comment (DmytroNazarenko) [inline agent/oracle.mjs]: Switch to camelCase, please

File: agent/pwa.mjs [hunk 95]
```diff
@@ -0,0 +1,366 @@
...
+        "s2m": {
+            "isInProgress": false,
+            "ts": 0
+        },
+        "s2s": {
+            "mapS2S": {
+                // 0: {
+                //     "isInProgress": false,
+                //     "ts": 0,
+                // }
```
Comment (DmytroNazarenko) [inline agent/pwa.mjs]: Remove redundant comments

File: agent/pwa.mjs [hunk 96]
```diff
@@ -0,0 +1,366 @@
...
+        const joProps = getNodeProgressAndTimestamp( joNode, strLoopWorkType, nIndexS2S );
+        if( imaState.isPrintPWA ) {
+            log.write(
+                cc.debug( "PWA loop-" ) + cc.attention( se ) +
+                cc.debug( " state arrived for node " ) + cc.info( nNodeNumber ) +
+                cc.debug( ", PWA state " ) + cc.j( joNode.pwaState ) +
+                cc.debug( ", arrived signature is " ) + cc.j( signature ) + "\n" );
+        }
+        const strMessageHash =
+            imaBLS.keccak256_4_pending_work_analysis(
```
Comment (DmytroNazarenko) [inline agent/pwa.mjs]: Switch to camelCase, please

File: agent/rpc-call.mjs [hunk 97]
```diff
@@ -0,0 +1,588 @@
...
+            const u = new URL( joCall.url );
+            const options = {
+                "hostname": u.hostname,
+                "port": u.port,
+                "path": "/",
+                "method": "POST",
+                "headers": {
+                    "Content-Type": "application/json"
+                    // "Accept": "*/*",
+                    // "Content-Length": strBody.length,
```
Comment (DmytroNazarenko) [inline agent/rpc-call.mjs]: Remove redundant comments

File: agent/rpc-call.mjs [hunk 98]
```diff
@@ -0,0 +1,588 @@
...
+    } );
+}
+
+export async function checkTcp( strHost, nPort, nTimeoutMilliseconds, isLog ) {
+    let isOnline = false;
+    try {
+        const promise_tcp = checkTcpPromise( strHost, nPort, nTimeoutMilliseconds, isLog )
+            .then( () => ( isOnline = true ) )
+            .catch( () => ( isOnline = false ) )
+            //.finally( () => console.log( { isOnline } ) )
```
Comment (DmytroNazarenko) [inline agent/rpc-call.mjs]: Remove redundant comments

File: agent/state.mjs [hunk 99]
```diff
@@ -0,0 +1,306 @@
...
+            "strPathJsonErc1155": ""
+        },
+        "sc": {
+            "joAccount": {
+                "privateKey":
+                    owaspUtils.toEthPrivateKey( process.env.PRIVATE_KEY_FOR_SCHAIN ),
+                "address": owaspUtils.fnAddressImpl_,
+                "strTransactionManagerURL":
+                    owaspUtils.toStringURL( process.env.TRANSACTION_MANAGER_URL_S_CHAIN ),
+                "tm_priority":
```
Comment (DmytroNazarenko) [inline agent/state.mjs]: Switch to camelCase, please

File: agent/state.mjs [hunk 100]
```diff
@@ -0,0 +1,306 @@
...
+        "jo_message_proxy_s_chain": null,
+        "jo_message_proxy_s_chain_target": null, // only s-chain target
+        "jo_token_manager_linker": null,
+        "jo_token_manager_linker_target": null, // only s-chain target
+        "eth_erc20": null, // only s-chain
+        // "eth_erc721": null, // only s-chain
+        // "eth_erc1155": null, // only s-chain
+        "eth_erc20_target": null, // only s-chain target
+        // "eth_erc721_target": null, // only s-chain target
+        // "eth_erc1155_target": null, // only s-chain target
```
Comment (DmytroNazarenko) [inline agent/state.mjs]: Switch to camelCase, please and remove redundant comments

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
Switch to camelCase and remove redundant comments, please

File: agent/bls.mjs (hunk 54 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 55 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 56 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 57 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 58 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 59 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 60 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 61 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 63 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 64 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 66 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 67 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 68 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 69 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/bls.mjs (hunk 70 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/cli.mjs (hunk 71 above)
Comment (sergiy-skalelabs) [reply agent/cli.mjs]: Fixed

File: agent/loop.mjs (hunk 72 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 73 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 76 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/pwa.mjs (hunk 96 above)
Comment (sergiy-skalelabs) [reply agent/pwa.mjs]: Fixed

File: agent/rpc-call.mjs (hunk 97 above)
Comment (sergiy-skalelabs) [reply agent/rpc-call.mjs]: Fixed

File: agent/rpc-call.mjs (hunk 98 above)
Comment (sergiy-skalelabs) [reply agent/rpc-call.mjs]: Fixed

File: agent/state.mjs (hunk 99 above)
Comment (sergiy-skalelabs) [reply agent/state.mjs]: Fixed

File: agent/state.mjs (hunk 100 above)
Comment (sergiy-skalelabs) [reply agent/state.mjs]: Fixed

File: agent/bls.mjs (hunk 62 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/loop.mjs (hunk 75 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 77 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 78 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Yes, it's in `loopWorker.mjs` in same folder

File: agent/loop.mjs (hunk 79 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 80 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 81 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 82 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/loop.mjs (hunk 83 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/main.mjs (hunk 89 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed

File: agent/main.mjs (hunk 90 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed

File: agent/oracle.mjs (hunk 93 above)
Comment (sergiy-skalelabs) [reply agent/oracle.mjs]: Fixed

File: agent/pwa.mjs (hunk 95 above)
Comment (sergiy-skalelabs) [reply agent/pwa.mjs]: Fixed

File: agent/loop.mjs (hunk 84 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed

File: agent/oracle.mjs (hunk 94 above)
Comment (sergiy-skalelabs) [reply agent/oracle.mjs]: Fixed

File: agent/main.mjs (hunk 91 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed

File: agent/main.mjs (hunk 88 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed

File: agent/loop_worker.mjs (hunk 86 above)
Comment (sergiy-skalelabs) [reply agent/loop_worker.mjs]: Fixed

File: agent/loop_worker.mjs (hunk 85 above)
Comment (sergiy-skalelabs) [reply agent/loop_worker.mjs]: Fixed

File: agent/bls.mjs (hunk 65 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Fixed

File: agent/loop.mjs (hunk 74 above)
Comment (sergiy-skalelabs) [reply agent/loop.mjs]: Fixed, removed everywhere

File: agent/main.mjs (hunk 87 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed, removed everywhere

File: agent/main.mjs (hunk 92 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed, removed everywhere

File: Dockerfile (hunk 25 above)
Comment (sergiy-skalelabs) [reply Dockerfile]: Fixed, removed comment

File: agent/bls.mjs [hunk 101]
```diff
@@ -0,0 +1,2987 @@
...
+}
+
+async function gatherSigningFinishImpl( optsSignOperation ) {
+    optsSignOperation.details.write( optsSignOperation.strLogPrefix +
+        cc.debug( "Will await for message BLS verification and sending..." ) +
+        "\n" );
+    await withTimeout(
+        "BLS verification and sending",
+        optsSignOperation.promiseCompleteGathering,
+        g_secondsMessageVerifySendTimeout )
```
Comment (DmytroNazarenko) [inline agent/bls.mjs]: Maybe let's put global vars the same camel case as others: gSeconds...

File: agent/loopWorker.mjs [hunk 102]
```diff
@@ -0,0 +1,212 @@
...
+            self.log(
+                cc.debug( "Full init compete for in-worker IMA loop" ) +
+                " " + cc.notice( workerData.url ) +
+                "\n" );
+            return joAnswer;
+        };
+        self.mapApiHandlers.schainsCached = function( joMessage, joAnswer, eventData, socket ) {
+            skaleObserver.setLastCachedSChains( joMessage.message.arrSChainsCached );
+        };
+        self.mapApiHandlers.skale_imaNotifyLoopWork =
```
Comment (DmytroNazarenko) [inline agent/loopWorker.mjs]: Change to camel case, please

File: agent/main.mjs [hunk 103]
```diff
@@ -0,0 +1,2921 @@
...
+    } );
+}
+
+function commandLineTaskDiscoverChainId() {
+    const imaState = state.get();
+    imaState.arrActions.push( {
+        "name": "Discover chains ID(s)",
+        "fn": async function() {
+            const strLogPrefix = cc.info( "Discover chains ID(s):" ) + " ";
+            const arr_urls_to_discover = [];
```
Comment (DmytroNazarenko) [inline agent/main.mjs]: Change to CamelCase please

File: agent/pwa.mjs [hunk 104]
```diff
@@ -0,0 +1,344 @@
...
+
+function computeWalkNodeIndices( nNodeNumber, nNodesCount ) {
+    if( nNodesCount <= 1 )
+        return []; // PWA is N/A
+    if( !( nNodeNumber >= 0 && nNodeNumber < nNodesCount ) )
+        return []; // PWA is N/A
+    let i = nNodeNumber - 1;
+    if( i < 0 )
+        i = nNodesCount - 1;
+    const arr_walk_node_indices = [];
```
Comment (DmytroNazarenko) [inline agent/pwa.mjs]: Change to CamelCase, please

File: agent/pwa.mjs [hunk 105]
```diff
@@ -0,0 +1,344 @@
...
+        if( imaState.nNodesCount <= 1 )
+            return true; // PWA is N/A
+        if( !( imaState.nNodeNumber >= 0 && imaState.nNodeNumber < imaState.nNodesCount ) )
+            return true; // PWA is N/A
+        if( ! imaState.joSChainNetworkInfo )
+            return true; // PWA is N/A
+        const jarrNodes = imaState.joSChainNetworkInfo.network;
+        if( ! jarrNodes )
+            throw new Error( "S-Chain network info is not available yet to PWA" );
+        const arr_busy_node_indices = [];
```
Comment (DmytroNazarenko) [inline agent/pwa.mjs]: Change to CamelCase, please

File: agent/utils.mjs [hunk 106]
```diff
@@ -0,0 +1,659 @@
...
+    strPath = strPath.replace( /^~/, os.homedir() );
+    strPath = path.normalize( strPath );
+    strPath = path.resolve( strPath );
+    return strPath;
+}
+
+export function getRandomFileName() {
+    const timestamp = new Date().toISOString().replace( /[-:.]/g,"" );
+    const random = ( "" + Math.random() ).substring( 2, 8 );
+    const random_number = timestamp + random;
```
Comment (DmytroNazarenko) [inline agent/utils.mjs]: Change to CamelCase, please

File: agent/utils.mjs [hunk 107]
```diff
@@ -0,0 +1,659 @@
...
+        "address" in tokenERC20SC && typeof tokenERC20SC.address == "string"
+    ) {
+        log.write(
+            cc.warning( "Skipping automatic " ) + cc.notice( "ERC20" ) +
+            cc.warning( " instantiation discovery, already done before" ) +
+            "\n" );
+        return;
+    }
+    const addressCallFrom = joAccountSC.address();
+    const address_on_s_chain =
```
Comment (DmytroNazarenko) [inline agent/utils.mjs]: Change to CamelCase, please

File: npms/skale-cc/cc.mjs [hunk 108]
```diff
@@ -0,0 +1,992 @@
...
+    return s2;
+}
+
+function errFnName( s ) {
+    if( s.indexOf( "async " ) == 0 )
+        return bright( "async" ) + " " + errFnDottedName( s.substring( 6 ) );
+    return errFnDottedName( s );
+}
+
+function err_loc_ln( s, isWithBraces ) {
```
Comment (DmytroNazarenko) [inline npms/skale-cc/cc.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 109]
```diff
@@ -109,27 +82,22 @@ const update_socket_data_stats_for_message = function( joMessage, joStats ) {
     else
         joStats[strMethod] = 1;
 };
-const generate_socket_data_stats_JSON = function( jo ) {
+export const generateSocketDataStatsJSON = function( jo ) {
     const joStats = {};
-    //let cnt = 1;
     if( "arr_packed_messages" in jo &&
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 110]
```diff
@@ -244,10 +214,11 @@ class BasicSocketPipe extends EventDispatcher {
...
-        throw new Error( "BasicSocketPipe.impl_send() must be overridden but calling it was attempted" );
+    implSend( data ) {
+        throw new Error(
+            "BasicSocketPipe.implSend() must be overridden but calling it was attempted" );
     }
-    is_auto_flush() {
+    isAutoFlush() {
         if( this.maxAccumulatedMessagesCount <= 1 )
             return true;
         const cnt = this.arr_accumulated_messages.length;
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 111]
```diff
@@ -1184,52 +1404,55 @@ class WebSocketServerPipe extends BasicSocketPipe {
...
                 key: "" + key,
                 cert: "" + cert
                 // , ca: ...
             } );
             server.listen( nTcpPort );
-            this.ws_srv = new ws_mod.Server( { server } );
+            this.ws_srv = new wsModule.WebSocketServer( { server } );
         } else
-            this.ws_srv = new ws_mod.Server( { port: nTcpPort } );
+            this.ws_srv = new wsModule.WebSocketServer( { port: nTcpPort } );
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 112]
```diff
@@ -1897,14 +2341,27 @@ class RTCServerPeer extends RTCConnection {
...
+                        "participant": this,
+                        "idSomebodyOtherSide": "" + idSomebodyOtherSide
+                    }
+                } )
+        );
     }
     onError( err ) {
         if( this.rtcCreator ) {
             this.rtcCreator.onRtcPeerError( this, err );
             if( this.idOffer in this.rtcCreator.map_server_offers ) {
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 113]
```diff
@@ -1999,40 +2485,59 @@ class RTCCreator extends RTCActor {
                 console.log( "Unregister offer", idOffer, "(one of all, RTCCreator dispose)" );
             rtcPeer.dispose();
         }
-        for( const [ /*idSomebodyOtherSide*/, rtcPeer ] of Object.entries( this.map_server_peers ) )
+        for( const [ /*idSomebodyOtherSide*/, rtcPeer ] of
+            Object.entries( this.map_server_peers ) )
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 114]
```diff
@@ -2543,20 +3277,31 @@ class WebRTCServerAcceptor extends BasicServerAcceptor {
...
+        strSignalingServerURL, idRtcParticipant, offerOptions,
+        signalingOptions, peerConfiguration, peerAdditionalOptions
+    ) {
         super();
         this.strSignalingServerURL = utils.makeValidSignalingServerURL( strSignalingServerURL );
-        this.idRtcParticipant = "" + ( ( idRtcParticipant != null && idRtcParticipant != undefined && typeof idRtcParticipant == "string" && idRtcParticipant.length > 0 ) ? idRtcParticipant : utils.uuid_v4() );
+        this.idRtcParticipant = "" +
+            ( ( idRtcParticipant != null && idRtcParticipant != undefined &&
+                typeof idRtcParticipant == "string" && idRtcParticipant.length > 0 )
+                ? idRtcParticipant : utils.uuid_v4() );
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/socketUtils.mjs [hunk 115]
```diff
@@ -19,28 +19,30 @@
...
- * @file utils.js
+ * @file socketUtils.mjs
  * @copyright SKALE Labs 2019-Present
  */
 
-const { settings } = require( "./settings.js" );
+import { settings } from "./socketSettings.mjs";
 
-const uuid_v4 = function() {
+export const uuid_v4 = function() {
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socketUtils.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/testSocketSignalingServer.mjs.mjs [hunk 116]
```diff
@@ -512,107 +603,171 @@ class SignalingServer extends EventDispatcher {
...
+                            throw new Error(
+                                "only connected signaling clients can publish offers" );
+                        }
                         if( ! ( signalingClient.isCreator ) )
                             throw new Error( "only creator can publish offers" );
                         const joOfferInfo = {
-                            // ts: some time stamp
-                            offer: joMessage.offer,
-                            idOffer: 0 + joMessage.idOffer
+                            // "ts": some time stamp
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/testSocketSignalingServer.mjs.mjs]: Remove this, please

File: npms/skale-cool-socket/testSocketTypes.mjs [hunk 117]
```diff
@@ -0,0 +1,134 @@
...
+    client.send( joTestMessage );
+    await sleep( 100 );
+    const joReturnValue = {
+        worker: worker,
+        client: client
+    };
+    return joReturnValue;
+}
+
+async function test_web_socket() {
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/testSocketTypes.mjs]: Change to CamelCase, please

File: npms/skale-cool-socket/testSocketTypes.mjs [hunk 118]
```diff
@@ -0,0 +1,134 @@
...
+    client.send( joTestMessage );
+    await sleep( 100 );
+    const joReturnValue = {
+        server: server,
+        client: client
+    };
+    return joReturnValue;
+}
+
+async function test_worker() {
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/testSocketTypes.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 119]
```diff
@@ -0,0 +1,7638 @@
...
+            isVerbose: ( verboseGet() >= verboseReversed().information ) ? true : false,
+            isVerboseTraceDetails: ( verboseGet() >= verboseReversed().debug ) ? true : false
+        };
+        optsGasPriseSetup.details.write( cc.debug( "Will fetch " ) +
+            cc.info( "Main Net gas price" ) + cc.debug( " via call to " ) +
+            cc.info( "Oracle" ) + cc.debug( " with options " ) +
+            cc.j( oracleOpts ) + cc.debug( "..." ) + "\n" );
+        try {
+            optsGasPriseSetup.gasPriceOnMainNet = owaspUtils.ensureStartsWith0x(
+                ( await imaOracle.get_gas_price(
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 120]
```diff
@@ -0,0 +1,7638 @@
...
+export function createProgressiveEventsScanPlan( details, nLatestBlockNumber ) {
+    // assume Main Net mines 6 blocks per minute
+    const blocks_in_1_minute = 6;
+    const blocks_in_1_hour = blocks_in_1_minute * 60;
+    const blocks_in_1_day = blocks_in_1_hour * 24;
+    const blocks_in_1_week = blocks_in_1_day * 7;
+    const blocks_in_1_month = blocks_in_1_day * 31;
+    const blocks_in_1_year = blocks_in_1_day * 366;
+    const blocks_in_3_years = blocks_in_1_year * 3;
+    const arr_progressive_events_scan_plan_A = [
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 121]
```diff
@@ -0,0 +1,7638 @@
...
+        arr_progressive_events_scan_plan[arr_progressive_events_scan_plan.length - 1];
+        if( ! ( joLastPlan.nBlockFrom == 0 && joLastPlan.nBlockTo == "latest" ) ) {
+            arr_progressive_events_scan_plan.push(
+                { "nBlockFrom": 0, "nBlockTo": "latest", "type": "entire block range" } );
+        }
+    } else {
+        arr_progressive_events_scan_plan.push(
+            { "nBlockFrom": 0, "nBlockTo": "latest", "type": "entire block range" } );
+    }
+    return arr_progressive_events_scan_plan;
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 122]
```diff
@@ -0,0 +1,7638 @@
...
+    }
+    details.write( strLogPrefix +
+        cc.debug( "Will run " ) +
+        cc.attention( "progressive" ) + cc.debug( " scan..." ) +
+        "\n" );
+    details.write( strLogPrefix +
+        cc.debug( "Current latest block number is " ) +
+        cc.info( nLatestBlockNumber.toHexString() ) +
+        "\n" );
+    const arr_progressive_events_scan_plan =
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 123]
```diff
@@ -0,0 +1,7638 @@
...
+            optsPayedCall.details.write( optsPayedCall.strLogPrefix +
+                cc.debug( "Adjusted transaction: " ) + cc.j( txAdjusted ) +
+                "\n" );
+            if( redis == null )
+                redis = new Redis( optsPayedCall.joAccount.strTransactionManagerURL );
+            const priority = optsPayedCall.joAccount.nTmPriority || 5;
+            optsPayedCall.details.write( optsPayedCall.strLogPrefix +
+                cc.debug( "TM priority: " ) + cc.j( priority ) + "\n" );
+            try {
+                const [ tx_id, joReceiptFromTM ] =
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 124]
```diff
@@ -0,0 +1,7638 @@
...
+            cc.warning( r.status );
+        details.write( strPrefixDetails + strMsg + "\n" );
+        log.write( strPrefixLog + strMsg + "\n" );
+    }
+    if( ( !tmIsFinished( r ) ) || r.status == "DROPPED" ) {
+        log.write( cc.error( "TM - TX " ) + cc.info( txId ) +
+            cc.error( " was unsuccessful, wait failed" ) + "\n" );
+        return null;
+    }
+    const joReceipt = await safeGetTransactionReceipt( details, 10, ethersProvider, r.tx_hash );
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 125]
```diff
@@ -0,0 +1,7638 @@
...
+        const isIgnoreApprove = false;
+        const strErrorOfDryRunApprove =
+            await dryRunCall(
+                details, ethersProviderSrc,
+                "ERC721", contractERC721, "approve", arrArgumentsApprove,
+                joAccountSrc, strActionName, isIgnoreApprove,
+                gasPrice, estimatedGasApprove, weiHowMuchApprove, null );
+        if( strErrorOfDryRunApprove )
+            throw new Error( strErrorOfDryRunApprove );
+        const joReceipt_approve =
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 126]
```diff
@@ -0,0 +1,7638 @@
...
+        const strErrorOfDryRunTransferERC721 =
+            await dryRunCall(
+                details, ethersProviderSrc,
+                "TokenManagerERC721", joTokenManagerERC721Src,
+                "transferToSchainERC721", arrArgumentsTransfer,
+                joAccountSrc, strActionName, isIgnoreTransferERC721,
+                gasPrice, estimatedGasTransfer, weiHowMuchTransferERC721, null );
+        if( strErrorOfDryRunTransferERC721 )
+            throw new Error( strErrorOfDryRunTransferERC721 );
+        const joReceipt_transfer =
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 127]
```diff
@@ -0,0 +1,7638 @@
...
+        const isIgnoreApprove = false;
+        const strErrorOfDryRunApprove =
+            await dryRunCall(
+                details, ethersProviderSrc,
+                "ERC1155", contractERC1155, "setApprovalForAll", arrArgumentsApprove,
+                joAccountSrc, strActionName, isIgnoreApprove,
+                gasPrice, estimatedGasApprove, weiHowMuchApprove, null );
+        if( strErrorOfDryRunApprove )
+            throw new Error( strErrorOfDryRunApprove );
+        const joReceipt_approve =
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 128]
```diff
@@ -0,0 +1,7638 @@
...
+                        "canceling search for transfer events" ) + "\n";
+                optsTransfer.details.write( s );
+                if( log.id != optsTransfer.details.id )
+                    log.write( s );
+                break;
+            }
+        }
+        if( optsTransfer.nBlockAge > 0 ) {
+            let bSecurityCheckPassed = true;
+            const strActionName_old = "" + optsTransfer.strActionName;
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-ima/index.mjs [hunk 129]
```diff
@@ -0,0 +1,7638 @@
...
+                optsTransfer.details.write( optsTransfer.strLogPrefix +
+                    cc.debug( "Diff    TS is " ) + cc.info( tsDiff ) + "\n" );
+                optsTransfer.details.write( optsTransfer.strLogPrefix +
+                    cc.debug( "Expected diff " ) + cc.info( optsTransfer.nBlockAge ) + "\n" );
+                if( tsDiff < optsTransfer.nBlockAge )
+                    bSecurityCheckPassed = false;
+                optsTransfer.details.write( optsTransfer.strLogPrefix +
+                    cc.debug( "Block age check is " ) + ( bSecurityCheckPassed
+                    ? cc.success( "PASSED" ) : cc.error( "FAILED" ) ) + "\n" );
+            } ca
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to CamelCase, please

File: npms/skale-log/log.mjs [hunk 130]
```diff
@@ -0,0 +1,364 @@
...
+
+export function generateTimestampString( ts, isColorized ) {
+    isColorized =
+        ( typeof isColorized == "undefined" )
+            ? true : ( isColorized ? true : false );
+    ts = ( ts instanceof Date ) ? ts : new Date();
+    const cc_date = function( x ) { return isColorized ? cc.date( x ) : x; };
+    const cc_time = function( x ) { return isColorized ? cc.time( x ) : x; };
+    const cc_frac_time = function( x ) { return isColorized ? cc.frac_time( x ) : x; };
+    const cc_bright = function( x ) { return isColorized ? cc.bright( x ) : x; };
```
Comment (DmytroNazarenko) [inline npms/skale-log/log.mjs]: Change to CamelCase, please

File: npms/skale-observer/observer.mjs [hunk 131]
```diff
@@ -0,0 +1,1057 @@
...
+                rawResults.results[strRef1].callsReturnContext[idxResult].returnValues;
+            const values2 =
+                rawResults.results[strRef2].callsReturnContext[idxResult].returnValues;
+            const values3 =
+                rawResults.results[strRef3].callsReturnContext[idxResult].returnValues;
+            const nodeDict = {
+                "id": nodeId,
+                "name": values0[0],
+                "ip": owaspUtils.ipFromHex( values0[1] ),
+                "base_port": values0[3],
```
Comment (DmytroNazarenko) [inline npms/skale-observer/observer.mjs]: Change to CamelCase, please

File: npms/skale-observer/observer.mjs [hunk 132]
```diff
@@ -0,0 +1,1057 @@
...
+                    "\n" );
+            }
+        }
+    }
+    return arrSChains;
+}
+
+export async function filterSChainsMarkedAsConnected( arrSChains, opts ) {
+    owaspUtils.ensureObserverOptionsInitialized( opts );
+    const arr_connected_schains = [];
```
Comment (DmytroNazarenko) [inline npms/skale-observer/observer.mjs]: Change to CamelCase, please

File: test/agent/agent.py [hunk 133]
```diff
@@ -261,21 +294,24 @@ def transfer_erc20_from_schain_to_mainnet(self, token_contract, token_contract_o
...
                 balance == erc20.functions.balanceOf(destination_address).call():
             debug('Wait for erc20 payment')
-            sleep(1)
+            sleep( 1 )
         # start = time()
         # while (time() < start + timeout if timeout > 0 else True) and \
         #         self.blockchain.get_transactions_count_on_mainnet(destination_address) == tx_count:
         #     debug('Wait for erc20 payment')
-        #     sleep(1)
+        #     sleep( 1 )
```
Comment (DmytroNazarenko) [inline test/agent/agent.py]: Remove, please

File: test/agent/agent.py [hunk 134]
```diff
@@ -293,7 +329,7 @@ def transfer_erc721_from_schain_to_mainnet(self, token_contract, token_contract_
         destination_address = erc721.functions.ownerOf(token_id).call()
         # destination_address = self.blockchain.key_to_address(to_key)
```
Comment (DmytroNazarenko) [inline test/agent/agent.py]: Remove please

File: test/test_cases/send_erc20_from_schain_to_mainnet.py [hunk 135]
```diff
@@ -65,13 +69,15 @@ def _prepare(self):
...
 
         amount_of_eth = 90 * 10 ** 15
 
         self.agent.transfer_eth_from_mainnet_to_schain(self.config.mainnet_key,
                                                        self.config.schain_key,
                                                        amount_of_eth,
                                                        self.timeout)
+        sleep( 10 )
 
         # self.blockchain.add_eth_cost(self.config.schain_key,
```
Comment (DmytroNazarenko) [inline test/test_cases/send_erc20_from_schain_to_mainnet.py]: Remove please

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
Please, switch commented lines to camelCase and remove redundant comments

File: agent/bls.mjs (hunk 101 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Yes, fixed

File: agent/loopWorker.mjs (hunk 102 above)
Comment (sergiy-skalelabs) [reply agent/loopWorker.mjs]: Fixed

File: agent/main.mjs (hunk 103 above)
Comment (sergiy-skalelabs) [reply agent/main.mjs]: Fixed

File: agent/pwa.mjs (hunk 104 above)
Comment (sergiy-skalelabs) [reply agent/pwa.mjs]: Fixed

File: agent/pwa.mjs (hunk 105 above)
Comment (sergiy-skalelabs) [reply agent/pwa.mjs]: Fixed

File: agent/utils.mjs (hunk 106 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Fixed

File: agent/utils.mjs (hunk 107 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 109 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cc/cc.mjs (hunk 108 above)
Comment (sergiy-skalelabs) [reply npms/skale-cc/cc.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 110 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 111 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 112 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 113 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 114 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socketUtils.mjs (hunk 115 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socketUtils.mjs]: Fixed

File: npms/skale-cool-socket/testSocketSignalingServer.mjs.mjs (hunk 116 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/testSocketSignalingServer.mjs.mjs]: Fixed

File: npms/skale-cool-socket/testSocketTypes.mjs (hunk 117 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/testSocketTypes.mjs]: Fixed

File: npms/skale-cool-socket/testSocketTypes.mjs (hunk 118 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/testSocketTypes.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 119 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 120 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 121 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 122 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 123 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 124 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: `r.tx_hash` is not our... we do not own it

File: npms/skale-ima/index.mjs (hunk 125 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 126 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 127 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 128 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 129 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-log/log.mjs (hunk 130 above)
Comment (sergiy-skalelabs) [reply npms/skale-log/log.mjs]: Fixed

File: npms/skale-observer/observer.mjs (hunk 131 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Fixed

File: npms/skale-observer/observer.mjs (hunk 132 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Fixed

File: test/agent/agent.py (hunk 133 above)
Comment (sergiy-skalelabs) [reply test/agent/agent.py]: Fixed

File: test/agent/agent.py (hunk 134 above)
Comment (sergiy-skalelabs) [reply test/agent/agent.py]: Fixed

File: test/test_cases/send_erc20_from_schain_to_mainnet.py (hunk 135 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc20_from_schain_to_mainnet.py]: Fixed

File: npms/skale-cc/cc.mjs [hunk 136]
```diff
@@ -0,0 +1,992 @@
...
+    gMapColorDefinitions.fgGreen,
+    gMapColorDefinitions.enlight + gMapColorDefinitions.fgCyan,
+    gMapColorDefinitions.fgCyan,
+    gMapColorDefinitions.enlight + gMapColorDefinitions.fgBlue,
+    gMapColorDefinitions.fgBlue,
+    gMapColorDefinitions.enlight + gMapColorDefinitions.fgMagenta,
+    gMapColorDefinitions.fgMagenta
+];
+
+export function rainbow_part( s, i ) {
```
Comment (DmytroNazarenko) [inline npms/skale-cc/cc.mjs]: Change to camelCase please

File: npms/skale-cc/cc.mjs [hunk 137]
```diff
@@ -0,0 +1,992 @@
...
+    const d = new Date();
+    const ts = Math.floor( ( d ).getTime() );
+    return ts;
+}
+
+export function ts_unix() {
+    const d = new Date();
+    const ts = Math.floor( ( d ).getTime() / 1000 );
+    return ts;
+}
```
Comment (DmytroNazarenko) [inline npms/skale-cc/cc.mjs]: Change to camelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 138]
```diff
@@ -109,27 +82,22 @@ const update_socket_data_stats_for_message = function( joMessage, joStats ) {
...
-        jo.arr_packed_messages &&
-        typeof jo.arr_packed_messages == "object"
+    if( "arrPackedMessages" in jo &&
+        jo.arrPackedMessages &&
+        typeof jo.arrPackedMessages == "object"
     ) {
-        //cnt = jo.arr_packed_messages.length;
-        for( const joMessage of jo.arr_packed_messages )
-            update_socket_data_stats_for_message( joMessage, joStats );
+        //cnt = jo.arrPackedMessages.length;
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Remove, please

File: npms/skale-cool-socket/socket.mjs [hunk 139]
```diff
@@ -1089,19 +1302,20 @@ class LocalSocketClientPipe extends DirectPipe {
...
         super.dispose();
     }
 };
 
-//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-
-class WebSocketServerPipe extends BasicSocketPipe {
+export class WebSocketServerPipe extends BasicSocketPipe {
     constructor( acceptor, ws_conn, remoteAddress ) {
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to camelCase, please

File: npms/skale-cool-socket/socket.mjs [hunk 140]
```diff
@@ -1184,52 +1404,55 @@ class WebSocketServerPipe extends BasicSocketPipe {
...
         ) {
-            const server = https_mod.createServer( {
+            const server = httpsModule.createServer( {
                 key: "" + key,
                 cert: "" + cert
                 // , ca: ...
             } );
             server.listen( nTcpPort );
-            this.ws_srv = new ws_mod.Server( { server } );
+            this.ws_srv = new wsModule.WebSocketServer( { server } );
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to camelCase

File: npms/skale-cool-socket/socket.mjs [hunk 141]
```diff
@@ -1496,21 +1742,30 @@ class RTCConnection extends EventDispatcher {
...
     onDataChannelError( event ) {
-        this.dispatchEvent( new UniversalDispatcherEvent( "dataChannelError", { detail: { actor: this } } ) );
+        this.dispatchEvent(
+            new UniversalDispatcherEvent(
+                "dataChannelError", { "detail": { "actor": this } } ) );
         this.onError( "Data channel error " + event.toString() );
     }
     onDataChannelMessage( event ) {
         if( event.data.size ) {
             // fileReceiver.receive( event.data, { } );
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Remove please

File: npms/skale-cool-socket/socket.mjs [hunk 142]
```diff
@@ -2148,9 +2720,13 @@ class RTCJoiner extends RTCActor {
...
-            ? "rtc-joiner"
-            : strInstanceType;
+        strInstanceType =
+            ( strInstanceType == null ||
+                strInstanceType == undefined ||
+                ( typeof strInstanceType != "string" ) ||
+                strInstanceType.length == 0 )
+                ? "rtc-joiner"
+                : strInstanceType;
         // arrAdditionalProps = arrAdditionalProps || [];
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Remove please

File: npms/skale-cool-socket/socket.mjs [hunk 143]
```diff
@@ -2593,26 +3341,46 @@ class WebRTCClientPipe extends BasicSocketPipe {
     rtc_connect( strSignalingServerURL ) {
```
Comment (DmytroNazarenko) [inline npms/skale-cool-socket/socket.mjs]: Change to camelCase

File: npms/skale-observer/observer.mjs [hunk 144]
```diff
@@ -0,0 +1,1056 @@
...
+        );
+        const strRef0 = "Nodes-nodes";
+        const strRef1 = "Nodes-getNodeDomainName";
+        const strRef2 = "Nodes-isNodeInMaintenance";
+        const strRef3 = "SchainsInternal-getSchainHashesForNode";
+        const contractCallContext = [
+            {
+                reference: strRef0,
+                contractAddress: opts.imaState.joNodes.address,
+                // abi:find_one_function_abi( opts.imaState.joAbiSkaleManager.nodes_abi, "nodes" ),
```
Comment (DmytroNazarenko) [inline npms/skale-observer/observer.mjs]: Remove, please

File: npms/skale-observer/observer.mjs [hunk 145]
```diff
@@ -0,0 +1,1056 @@
...
+    return idxNode;
+}
+export function pickRandomSChainNode( joSChain ) {
+    const idxNode = pickRandomSChainNodeIndex( joSChain );
+    return joSChain.data.computed.nodes[idxNode];
+}
+
+export function pickRandomSChainUrl( joSChain ) {
+    const joNode = pickRandomSChainNode( joSChain );
+    return "" + joNode.http_endpoint_ip;
```
Comment (DmytroNazarenko) [inline npms/skale-observer/observer.mjs]: Change to camelCase

File: npms/skale-ima/index.mjs [hunk 146]
```diff
@@ -0,0 +1,7649 @@
...
+            return false;
+        if( optsTransfer.nBlockAwaitDepth > 0 ) {
+            let bSecurityCheckPassed = true;
+            const strActionNameOld = "" + optsTransfer.strActionName;
+            optsTransfer.strActionName = "security check: evaluate block depth";
+            try {
+                const transactionHash = r[0].transactionHash;
+                if( log.verboseGet() >= log.verboseReversed().debug ) {
+                    optsTransfer.details.write( optsTransfer.strLogPrefix +
+                        cc.debug( "Event transactionHash is " ) +
```
Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to camelCase

Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to camelCase

Comment (DmytroNazarenko) [inline npms/skale-ima/index.mjs]: Change to camelCase

File: npms/skale-observer/observer.mjs (hunk 145 above)
Comment (DmytroNazarenko) [inline npms/skale-observer/observer.mjs]: Change to camelCase

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
Change to camelCase and remove some comments, please

File: npms/skale-ima/index.mjs (hunk 129 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-cc/cc.mjs (hunk 136 above)
Comment (sergiy-skalelabs) [reply npms/skale-cc/cc.mjs]: Fixed

File: npms/skale-cc/cc.mjs (hunk 137 above)
Comment (sergiy-skalelabs) [reply npms/skale-cc/cc.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 138 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 139 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 140 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-observer/observer.mjs (hunk 145 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Fixed, switched to `array[ "access_notation" ]` for comparibility with old similar JSON RPC answer format generated by `skaled`.

File: npms/skale-ima/index.mjs (hunk 146 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 141 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 142 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

File: npms/skale-observer/observer.mjs (hunk 144 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Fixed

File: npms/skale-ima/index.mjs (hunk 146 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Fixed

File: npms/skale-observer/observer.mjs (hunk 145 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Fixed

File: npms/skale-cool-socket/socket.mjs (hunk 143 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socket.mjs]: Fixed

**Review by DmytroNazarenko — DISMISSED** [review]
Great job!

**Review by kladkogex — DISMISSED** [review]

File: .github/workflows/main.yml [hunk 147]
```diff
@@ -350,7 +346,7 @@ jobs:
     - name: Start background ganache
       run: |
         cd proxy
-        NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 12000000 --quiet --allowUnlimitedContractSize --acctKeys ../test/accounts.json &
+        NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 0xfffffffffff --quiet --allowUnlimitedContractSize --defaultBalanceEther 2000000 --account="0x23ABDBD3C61B5330AF61EBE8BEF582F4E5CC08E554053A718BDCE7813B9DC1FC,1000000000000000000000000000000000" --account="0x80ebc2e00b8f13c5e2622b5694ab63ee80f7c5399554d2a12feeb0212eb8c69e,1000000000000000000000000000000000" --acctKeys ../test/accounts.json &
```
Comment (payvint) [inline .github/workflows/main.yml]: What is the reason to have static private keys and do not use it from accounts.json or from secret variables from github?

Comment (payvint) [reply .github/workflows/main.yml]: Why gas limit was increased 12M not enough?

File: Dockerfile [hunk 148]
```diff
@@ -1,7 +1,19 @@
...
 RUN apt-get update
-RUN apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
+RUN apt-get install --no-install-recommends -yq software-properties-common
+RUN apt-get update
+RUN apt-get install --no-install-recommends -y build-essential=12 zlib1g-dev=1 libncurses5-dev=6 libgdbm-dev=1 libnss3-dev=2 libssl-dev=3 libreadline-dev=8 libffi-dev=3 wget=1 curl=7 sudo=1 git=1
+
+RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
+RUN apt-get install --no-install-recommends -y nodejs=16
+RUN node --version
+RUN npm --version
```
Comment (payvint) [inline Dockerfile]: Looks like npm is not necessary here - increase lines of code and decrease readability

File: Dockerfile [hunk 149]
```diff
@@ -30,11 +42,22 @@ RUN chmod +x /ima/bls_binaries/verify_bls
...
+WORKDIR /ima/npms/skale-owasp
+RUN yarn install
+WORKDIR /ima/npms/skale-observer
+RUN yarn install
+WORKDIR /ima/npms/skale-ima
+RUN yarn install
+WORKDIR /ima/agent
+RUN yarn install
+WORKDIR /ima
+RUN yarn install
```
Comment (payvint) [inline Dockerfile:47]: Looks like by this line all the previous folders would be installed, so you do not need each yarn install by each folder

File: agent/README.md [hunk 150]
```diff
@@ -501,8 +501,6 @@ node ./main.js --verbose=9 --expose --colors \
 --nodes-count=value.............S-Chain nodes count.
 --time-framing=value............Specifies period(in seconds) for time framing. Zero means disable time framing.
 --time-gap=value................Specifies gap(in seconds) before next time frame.
---ptx...........................Enable pending transaction analysis to avoid transaction conflicts.
```
Comment (payvint) [inline agent/README.md:504]: Was this feature removed? And why?

File: agent/run.sh [hunk 151]
```diff
@@ -85,8 +87,11 @@ BASE_OPTIONS="--gas-price-multiplier=$GAS_PRICE_MULTIPLIER \
 --address-main-net=$NODE_ADDRESS \
 --address-s-chain=$NODE_ADDRESS \
 --sign-messages \
+--gathered \
 --expose \
+--no-expose-security-info \
 --skip-dry-run \
+--ignore-dry-run \
```
Comment (payvint) [inline agent/run.sh]: Do we need skip-dry-run and ignore-dry-run?

File: agent/run.sh [hunk 152]
```diff
@@ -109,13 +114,9 @@ BASE_OPTIONS="--gas-price-multiplier=$GAS_PRICE_MULTIPLIER \
 --tm-url-main-net=$TM_URL_MAIN_NET \
 --time-gap=$TIME_GAP \
 --monitoring-port=$MONITORING_PORT \
---ptx \
---ptx-attempt=3 "
-
-#echo "Base options:"
-#echo "$BASE_OPTIONS"
+--pwa \
```
Comment (payvint) [inline agent/run.sh:116]: Looks like this command and the next one are not described in README

File: npms/skale-cool-socket/package.json [hunk 153]
```diff
@@ -6,9 +6,11 @@
     "license": "AGPL-3.0",
     "author": "SKALE Labs and contributors",
     "scripts": {
-        "lint-check": "eslint *.js",
-        "lint-fix": "eslint ./*.js --fix",
-        "test": "echo \"Error: no test specified\" && exit 1"
+        "lint-check": "eslint *.*js",
+        "lint-fix": "eslint ./*.*js --fix",
+        "test": "echo \"Error: no test specified\" && exit 1",
```
Comment (payvint) [inline npms/skale-cool-socket/package.json]: Do we need this command?

File: npms/skale-cool-socket/socketSettings.mjs [hunk 154]
```diff
@@ -81,13 +85,21 @@ const settings = {
             ] ,
             peerConfiguration: {
                 iceServers: [
-                    // { urls: "stun:192.168.88.220:3478", username: "webrtc", credential: "qwerty" }
-                    // { urls: "turn:192.168.88.220:3478", username: "webrtc", credential: "qwerty" }
-                    { urls: "stun:127.0.0.1:3478", username: "webrtc", credential: "qwerty" }
-                    // { urls: "turn:127.0.0.1:3478", username: "webrtc", credential: "qwerty" }
+                    // { urls: "stun:192.168.88.220:3478",
```
Comment (payvint) [inline npms/skale-cool-socket/socketSettings.mjs]: Are these comments necessary? If yes can you make a comment like "Examples" or "Alternatives"?

Comment (payvint) [reply npms/skale-cool-socket/socketSettings.mjs]: Relates to the all comments below as well till the line 112(included)

File: npms/skale-cool-socket/package.json (hunk 153 above)
Comment (payvint) [reply npms/skale-cool-socket/package.json]: I thought it would execute tests which are added to this folder

File: proxy/migrations/deploySkaleManagerComponents.ts [hunk 155]
```diff
@@ -185,7 +185,7 @@ async function main() {
     };
     await keyStorage.setBlsCommonPublicKeyForSchain( ethers.utils.solidityKeccak256(['string'], [schainName]), BLSPublicKey );
     console.log("Set common public key in KeyStorage contract", keyStorage.address, "\n");
-    await wallets.rechargeSchainWallet( web3.utils.soliditySha3( schainName ), { value: "1000000000000000000" } );
+    await wallets.rechargeSchainWallet( web3.utils.soliditySha3( schainName ), { value: "10000000000000000000" } ); // originally it was 10000000000000000000 = 1ETH
```
Comment (payvint) [inline proxy/migrations/deploySkaleManagerComponents.ts]: In comment you should decrease a number on 1 zero

File: test/agent/agent.py [hunk 156]
```diff
@@ -261,21 +294,19 @@ def transfer_erc20_from_schain_to_mainnet(self, token_contract, token_contract_o
...
                 'erc20-main-net': erc20_config_filename,
-                'erc20-s-chain': erc20_clone_config_filename
+                'erc20-s-chain': erc20_clone_config_filename,
+                'colors': None,
+                'no-skip-dry-run': None,
+                'ignore-dry-run': None
             }
         )
-        # sleep(30)
+        # sleep( 30 )
```
Comment (payvint) [inline test/agent/agent.py]: Delete unnecessary comment

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py [hunk 157]
```diff
@@ -31,8 +31,9 @@ def __init__(self, config):
         super().__init__('load_send_ether_from_mainnet_to_schain_and_back', config)
 
     def _execute(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
+        amountRecharge = 200 * 10 ** 18 # 2 * 10 ** 18
```
Comment (payvint) [inline test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: Why amount to recharge increased from 2 Eth to 200 Eth

File: test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py [hunk 158]
```diff
@@ -46,13 +46,14 @@ def _prepare(self):
         signed_txn = self.blockchain.web3_mainnet.eth.account.signTransaction(mint_txn,
                                                                               private_key=self.config.mainnet_key)
         self.blockchain.web3_mainnet.eth.sendRawTransaction(signed_txn.rawTransaction)
+        sleep( 10 )
         self.blockchain.disableWhitelistERC1155(self.config.mainnet_key, self.config.schain_name)
+        sleep( 10 )
         self.blockchain.enableAutomaticDeployERC1155(self.config.schain_key, "Mainnet")
+        sleep( 10 )
```
Comment (payvint) [inline test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py]: Why you added a lot of sleep function - it will increase tests execution In couple times - or do I miss something?

File: test/tools/blockchain.py [hunk 159]
```diff
@@ -384,7 +384,7 @@ def await_receipt(web3, tx, retries=10, timeout=5):
             receipt = BlockChain.get_receipt(web3, tx)
             if (receipt != None):
                 return receipt
-            time.sleep(timeout)
+            sleep( 3 ) # timeout
```
Comment (payvint) [inline test/tools/blockchain.py]: Change 3 to timeout

File: test/tools/test_case.py [hunk 160]
```diff
@@ -32,14 +33,16 @@ class TestCase:
     config = None
     time_started = time()
     timeout = None
+    timeout_of_entire_test = None
 
-    def __init__(self, name, config, timeout=80000):
+    def __init__(self, name, config, timeout=10, timeout_of_entire_test=80000):
```
Comment (payvint) [inline test/tools/test_case.py]: remove "timeout" input parameter because it is not used

**Review by payvint — CHANGES_REQUESTED** [review]
Will review the rest a bit later

File: .github/workflows/main.yml (hunk 147 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Will re-check gas limit. This is the only way to specifify private keys here, as far as I do understand.

File: Dockerfile (hunk 148 above)
Comment (sergiy-skalelabs) [reply Dockerfile]: `npm` version output here can be useful if we will come across with any problems installing packages. But we never had such problems yet.

File: Dockerfile (hunk 149 above)
Comment (sergiy-skalelabs) [reply Dockerfile:47]: Yes.

File: agent/README.md (hunk 150 above)
Comment (sergiy-skalelabs) [reply agent/README.md:504]: `--ptx` turns on pending transaction analysis subsystem. When each `n-th` IMA Agent queries `(n-1)th, (n-2)th, ...` whether it completed working. Needed to avoid `revert`s on submitting same IMA messages twice.

File: agent/run.sh (hunk 151 above)
Comment (sergiy-skalelabs) [reply agent/run.sh]: `--skip-dry-run` does not invoke any dry run at all.
`--ignore-dry-run` do invoke dry run everywhere, but ignore if it fails.
We cannot run normally without `--ignore-dry-run`, unfortunatelly.

File: agent/run.sh (hunk 152 above)
Comment (sergiy-skalelabs) [reply agent/run.sh:116]: yes, `--pwa` is new `--ptx`. It's pending work analysis.

File: npms/skale-cool-socket/package.json (hunk 153 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/package.json]: No. We don't need it. Because we have different groups of tests and some of them are non-JS tests. We can remove it.

File: npms/skale-cool-socket/socketSettings.mjs (hunk 154 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socketSettings.mjs]: No. We don't use web rtc in `socket.mjs`. Will remove it.

File: proxy/migrations/deploySkaleManagerComponents.ts (hunk 155 above)
Comment (sergiy-skalelabs) [reply proxy/migrations/deploySkaleManagerComponents.ts]: OK, sure

File: test/agent/agent.py (hunk 156 above)
Comment (sergiy-skalelabs) [reply test/agent/agent.py]: Yes, reasonable

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py (hunk 157 above)
Comment (sergiy-skalelabs) [reply test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: No idea. Will re-check. Probably 2ETH was not enough in some cases.

File: test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py (hunk 158 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py]: Elvis knows better). We wait for TX write down into DB. That's all we do.

File: test/tools/blockchain.py (hunk 159 above)
Comment (sergiy-skalelabs) [reply test/tools/blockchain.py]: ok

File: test/tools/test_case.py (hunk 160 above)
Comment (sergiy-skalelabs) [reply test/tools/test_case.py]: ok

File: Dockerfile (hunk 148 above)
Comment (sergiy-skalelabs) [reply Dockerfile]: I would prefer to have `npm --version` here. It prints 1 line of text only.

File: Dockerfile (hunk 149 above)
Comment (sergiy-skalelabs) [reply Dockerfile:47]: Fixed

File: agent/README.md (hunk 150 above)
Comment (sergiy-skalelabs) [reply agent/README.md:504]: It's not removed. It's renamed to `--pwa` and turned on by default and we never need to turn it off on real nodes.

File: agent/run.sh (hunk 152 above)
Comment (sergiy-skalelabs) [reply agent/run.sh:116]: We have PWA (pending work analysis) always turned on. It's bad idea to turn it of on real nodes.

File: npms/skale-cool-socket/package.json (hunk 153 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/package.json]: Removed "test". Fixed

File: npms/skale-cool-socket/socketSettings.mjs (hunk 154 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/socketSettings.mjs]: Removed. Thanks.

File: proxy/migrations/deploySkaleManagerComponents.ts (hunk 155 above)
Comment (sergiy-skalelabs) [reply proxy/migrations/deploySkaleManagerComponents.ts]: Fixed

File: test/agent/agent.py (hunk 156 above)
Comment (sergiy-skalelabs) [reply test/agent/agent.py]: Removed. Fixed.

File: test/tools/blockchain.py (hunk 159 above)
Comment (sergiy-skalelabs) [reply test/tools/blockchain.py]: Rolled back. Fixed.

File: test/tools/test_case.py (hunk 160 above)
Comment (sergiy-skalelabs) [reply test/tools/test_case.py]: No. It's used. See
```
    def __init__(self, name, config, timeout=10, timeout_of_entire_test=80000):
        self.name = name
        self.deployer = Deployer(config)
        self.agent = Agent(config)
        self.blockchain = BlockChain(config)
        self.config = config
        self.timeout = timeout ### <-------- here <-------- <-------- <--------
        self.timeout_of_entire_test = timeout_of_entire_test

```
Also, having `timeout` in constructor is standard in these py tests.

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py (hunk 157 above)
Comment (sergiy-skalelabs) [reply test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: Yes. `2 * 10 ** 18` was not enough. Will change to `20 * 10 ** 18` for now. Because 200 is really a lot.

File: .github/workflows/main.yml (hunk 147 above)
Comment (payvint) [reply .github/workflows/main.yml]: Why do you need to specify private keys?
You can get first 2 from the accounts.json and pass them to tests or in tests get first 2 from the accounts.json

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py (hunk 157 above)
Comment (payvint) [reply test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: Hmm, it was working before with 2Eth all these years, maybe something wrong with gas prices?

File: test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py (hunk 158 above)
Comment (payvint) [reply test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py]: These changes were performed in current PR

File: Dockerfile (hunk 148 above)
Comment (payvint) [reply Dockerfile]: So please leave only 1 line of npm --version

File: agent/README.md (hunk 150 above)
Comment (payvint) [reply agent/README.md:504]: Please add it to the README

File: agent/run.sh (hunk 151 above)
Comment (payvint) [reply agent/run.sh]: What it is the reason to keep both of the flags? If we can keep one and use it

File: agent/run.sh (hunk 152 above)
Comment (payvint) [reply agent/run.sh:116]: Please add it to the README

File: test/tools/test_case.py (hunk 160 above)
Comment (payvint) [reply test/tools/test_case.py]: So why do you implement a new variable `timeout_of_entire_test` if we can use the old one - as it was before the changes

Comment (sergiy-skalelabs) [reply test/tools/test_case.py]: `timeout_of_entire_test` is max time to run 1 test and wait it's complete
`timeout` is 1 operation timeout inside test
due to some reason these 2 timeouts were just 1 timeout previously
they are different

File: test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py (hunk 158 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc1155_batch_from_mainnet_to_schain.py]: will switch to `sleep( 5 )`, it should be enough

File: agent/run.sh (hunk 152 above)
Comment (sergiy-skalelabs) [reply agent/run.sh:116]: Added into MD. Also fixed lot of grammar errors there. Face palm.

File: agent/run.sh (hunk 151 above)
Comment (sergiy-skalelabs) [reply agent/run.sh]: Fixed. Will use `--skip-dry-run` like D1 always did while instantiating nodes.

File: agent/README.md (hunk 150 above)
Comment (sergiy-skalelabs) [reply agent/README.md:504]: Fixed

File: Dockerfile (hunk 148 above)
Comment (sergiy-skalelabs) [reply Dockerfile]: Fixed

Comment (sergiy-skalelabs) [reply Dockerfile]: Fixed

File: .github/workflows/main.yml (hunk 147 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Now using `--gasLimit 12000000` again. Fixed.

Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: We are using command line private keys because I did not found way to insert these two keys into `../test/accounts.json` file.

File: .github/workflows/main.yml [hunk 161]
```diff
@@ -350,7 +346,7 @@ jobs:
     - name: Start background ganache
       run: |
         cd proxy
-        NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 12000000 --quiet --allowUnlimitedContractSize --acctKeys ../test/accounts.json &
+        NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 12000000 --quiet --allowUnlimitedContractSize --defaultBalanceEther 2000000 --account="0x23ABDBD3C61B5330AF61EBE8BEF582F4E5CC08E554053A718BDCE7813B9DC1FC,1000000000000000000000000000000000" --account="0x80ebc2e00b8f13c5e2622b5694ab63ee80f7c5399554d2a12feeb0212eb8c69e,1000000000000000000000000000000000" --acctKeys ../test/accounts.json &
```
Comment (payvint) [inline .github/workflows/main.yml]: Try to remove

Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Fixed

File: .github/workflows/main.yml (hunk 147 above)
Comment (DimaStebaev) [reply .github/workflows/main.yml]: I see that `gasLimit` is still set to `0xfffffffffff`

Comment (DimaStebaev) [reply .github/workflows/main.yml]: > We are using command line private keys because I did not found way to insert these two keys into `../test/accounts.json` file.

ganache does it for you because of `acctKeys` flag.
From ganache documentation:
```
--account_keys_path, --acctKeys
saves generated accounts and private keys as JSON object in specified file
```

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py (hunk 157 above)
Comment (DimaStebaev) [reply test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: Agreed with Artem. It worth to figure out why 2 ETH is not enough. I'd say that even 2 ETH is a lot.

File: .github/workflows/main.yml (hunk 147 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Latest code is `NODE_OPTIONS="--max_old_space_size=3072" npx ganache-cli --gasLimit 12000000 --quiet --allowUnlimitedContractSize --defaultBalanceEther 2000000 --acctKeys ../test/accounts.json &`

Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: So, you commented obsolete version.

File: test/test_cases/send_ether_from_schain_to_mainnet.py [hunk 162]
```diff
@@ -33,8 +34,10 @@ def __init__(self, config):
         super().__init__('Send ether from schain to mainnet', config)
 
     def _prepare(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
+        sleep( 5 )
+        amountRecharge = 20 * 10 ** 18 # 2 * 10 ** 18
```
Comment (payvint) [inline test/test_cases/send_ether_from_schain_to_mainnet.py]: Can you please change it back here too

File: test/test_cases/send_erc721_from_schain_to_mainnet.py [hunk 163]
```diff
@@ -34,8 +34,10 @@ def __init__(self, config):
         super().__init__('Send ERC721 from schain to mainnet', config)
 
     def _prepare(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
+        sleep( 5 )
+        amountRecharge = 20 * 10 ** 18 # 2 * 10 ** 18
```
Comment (payvint) [inline test/test_cases/send_erc721_from_schain_to_mainnet.py]: Here as well

File: test/test_cases/send_erc20_from_schain_to_mainnet.py [hunk 164]
```diff
@@ -36,8 +36,10 @@ def __init__(self, config):
         super().__init__('Send ERC20 from schain to mainnet', config)
 
     def _prepare(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
+        sleep( 5 )
+        amountRecharge = 20 * 10 ** 18 # 2 * 10 ** 18
```
Comment (payvint) [inline test/test_cases/send_erc20_from_schain_to_mainnet.py]: Here too

File: test/test_cases/send_erc1155_from_schain_to_mainnet.py [hunk 165]
```diff
@@ -35,8 +35,10 @@ def __init__(self, config):
         super().__init__('Send ERC1155 from schain to mainnet', config)
 
     def _prepare(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
+        sleep( 5 )
+        amountRecharge = 20 * 10 ** 18 # 2 * 10 ** 18
```
Comment (payvint) [inline test/test_cases/send_erc1155_from_schain_to_mainnet.py]: Here also

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py [hunk 166]
```diff
@@ -31,19 +31,19 @@ def __init__(self, config):
         super().__init__('load_send_ether_from_mainnet_to_schain_and_back', config)
 
     def _execute(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
-        #
+        amountRecharge = 20 * 10 ** 18 # 2 * 10 ** 18
```
Comment (payvint) [inline test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: And here

File: agent/utils.mjs [hunk 167]
```diff
@@ -0,0 +1,659 @@
...
+    }
+    const addressCallFrom = joAccountSC.address();
+    const addressOnSChain =
+        await waitForClonedTokenToAppear(
+            sc, "erc1155", addressCallFrom, 40, tokensMN, strMainnetName );
+    tokenERC1155SC.abi = JSON.parse( JSON.stringify( tokensMN.joABI.ERC1155_abi ) );
+    tokenERC1155SC.address = "" + addressOnSChain;
+}
+
+export function encodeUTF8( s ) {
```
Comment (payvint) [inline agent/utils.mjs]: Maybe we can change to https://www.npmjs.com/package/utf8

File: agent/utils.mjs [hunk 168]
```diff
@@ -0,0 +1,659 @@
...
+            } else
+                arrBytes[i++] = c >> 12 | 224;
+            arrBytes[i++] = c >> 6 & 63 | 128;
+        }
+        arrBytes[i++] = c & 63 | 128;
+    }
+    return arrBytes.subarray( 0, i );
+}
+
+export function decodeUTF8( arrBytes ) {
```
Comment (payvint) [inline agent/utils.mjs]: Here as well https://www.npmjs.com/package/utf8

File: agent/utils.mjs [hunk 169]
```diff
@@ -0,0 +1,659 @@
...
+        } else {
+            throw new Error(
+                "UTF-8 decode: code point 0x" +
+                c.toString( 16 ) + " exceeds UTF-16 reach" );
+        }
+    }
+    return s;
+}
+
+export function hexToBytes( strHex, isInversiveOrder ) { // convert a hex string to a byte array
```
Comment (payvint) [inline agent/utils.mjs:314]: I will propose to change with standard functions from ethers or crypto.js

File: agent/utils.mjs [hunk 170]
```diff
@@ -0,0 +1,659 @@
...
+    let i, j;
+    const arrBytes = new Uint8Array( cnt / 2 );
+    for( i = 0, j = 0; i < cnt; ++j, i += 2 )
+        arrBytes[j] = parseInt( strHex.substr( i, 2 ), 16 );
+    if( isInversiveOrder )
+        invertArrayItemsLR( arrBytes );
+    return arrBytes;
+}
+
+export function bytesToHex( arrBytes, isInversiveOrder ) { // convert a byte array to a hex string
```
Comment (payvint) [inline agent/utils.mjs:335]: Here as well

File: agent/utils.mjs [hunk 171]
```diff
@@ -0,0 +1,659 @@
...
+
+export function bytesAlignLeftWithZeroes( arrBytes, cntMin ) {
+    const arrOneZeroByte = new Uint8Array( 1 );
+    arrOneZeroByte[0] = 0;
+    while( arrBytes.length < cntMin )
+        arrBytes = bytesConcat( arrOneZeroByte, arrBytes );
+    return arrBytes;
+}
+
+export function bytesAlignRightWithZeroes( arrBytes, cntMin ) {
```
Comment (payvint) [inline agent/utils.mjs:365]: You can change it to ethers.utils.zeroPad

File: agent/utils.mjs [hunk 172]
```diff
@@ -0,0 +1,659 @@
...
+            hex.push( c1 );
+        }
+    }
+    return hex.join( "" );
+}
+
+export function bytesAlignLeftWithZeroes( arrBytes, cntMin ) {
+    const arrOneZeroByte = new Uint8Array( 1 );
+    arrOneZeroByte[0] = 0;
+    while( arrBytes.length < cntMin )
```
Comment (payvint) [inline agent/utils.mjs]: You can remove loop here

File: agent/utils.mjs [hunk 173]
```diff
@@ -0,0 +1,659 @@
...
+    return concatTypedArrays( ui8a, b );
+}
+
+export function bytesConcat( a1, a2 ) {
+    a1 = a1 || new Uint8Array();
+    a2 = a2 || new Uint8Array();
+    return concatTypedArrays( a1, a2 );
+}
+
+export function toArrayBuffer( buf ) {
```
Comment (payvint) [inline agent/utils.mjs]: Check here to use standard functions instead of loops
https://stackoverflow.com/questions/37228285/uint8array-to-arraybuffer

File: agent/utils.mjs [hunk 174]
```diff
@@ -0,0 +1,659 @@
...
+    // https://stackoverflow.com/questions/8609289
+    //          /convert-a-binary-nodejs-buffer-to-javascript-arraybuffer
+    const ab = new ArrayBuffer( buf.length );
+    const view = new Uint8Array( ab );
+    for( let i = 0; i < buf.length; ++i )
+        view[i] = buf[i];
+    return ab;
+}
+
+export function toBuffer( ab ) {
```
Comment (payvint) [inline agent/utils.mjs:398]: Looks like can be changed like this
`return Buffer.from( new Uint8Array( ab ) );`

File: agent/utils.mjs [hunk 175]
```diff
@@ -0,0 +1,659 @@
...
+    const buf = Buffer.alloc( ab.byteLength );
+    const view = new Uint8Array( ab );
+    for( let i = 0; i < buf.length; ++i )
+        buf[i] = view[i];
+    return buf;
+}
+
+export function invertArrayItemsLR( arr ) {
```
Comment (payvint) [inline agent/utils.mjs]: I think you can use standard function `reverse()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse

File: agent/utils.mjs [hunk 176]
```diff
@@ -0,0 +1,659 @@
...
+    }
+    return arr;
+}
+
+// see: https://developer.chrome.com/blog/how-to-convert-arraybuffer-to-and-from-string/
+export function ab2str( buf ) {
+    return String.fromCharCode.apply( null, new Uint16Array( buf ) );
+}
+
+export function str2ab( str ) {
```
Comment (payvint) [inline agent/utils.mjs]: I would suggest to use TextEncoder and then uint8buffer to array buffer
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

File: agent/pwa.mjs [hunk 177]
```diff
@@ -0,0 +1,358 @@
...
+ */
+
+/**
+ * @file pwa.mjs
+ * @copyright SKALE Labs 2019-Present
+ */
+
+import * as cc from "../npms/skale-cc/cc.mjs";
+import * as log from "../npms/skale-log/log.mjs";
+import * as owaspUtils from "../npms/skale-owasp/owaspUtils.mjs";
```
Comment (payvint) [inline agent/pwa.mjs]: Let's change to importing only extractErrorMessge, because right now it importing everything in owaspUtils including ethersMod

File: agent/rpcCall.mjs [hunk 178]
```diff
@@ -0,0 +1,587 @@
...
+/**
+ * @file rpcCall.mjs
+ * @copyright SKALE Labs 2019-Present
+ */
+
+import * as ws from "ws";
+import * as urllib from "urllib";
+import * as https from "https";
+import * as net from "net";
+import * as owaspUtils from "../npms/skale-owasp/owaspUtils.mjs";
```
Comment (payvint) [inline agent/rpcCall.mjs]: Here as well - just import isUrlWS and validateURL

File: agent/CLI.md [hunk 179]
```diff
@@ -6,288 +6,298 @@
...
+    --s2s-disable...................Disables S-Chain to S-Chain transfers.
+    --net-rediscover=number.........SKALE NETWORK re-discovery interval(in seconds). Default is 3600 seconds or 1 hour, specify 0 to disable SKALE NETWORK re-discovery.
+```
+
+**IMA** loop can optionally use dry run, group **IMA** messages and supports various customizations:
+
+```text
+    --no-wait-s-chain...............Do not wait until S-Chain is started.
+    --max-wait-attempts=value.......Max number of S-Chain call attempts to do while it became alive and sane.
+    --skip-dry-run..................Skip dry run contract method calls.
```
Comment (payvint) [inline agent/CLI.md:197]: Maybe let's remove skip-dry-run - as I understand we can just not providing dry-run

File: test/agent/agent.py [hunk 180]
```diff
@@ -40,7 +40,14 @@ def __init__(self, config):
         self.blockchain = BlockChain(config)
 
     def register(self):
-        self._execute_command('register')
+        self._execute_command(
+            'register',
+            {
+                'colors': None,
```
Comment (payvint) [inline test/agent/agent.py]: So by default colors are turned on?
Looks like no-skip-dry-run is outdated param

File: agent/test/get_main_net.spec.js [hunk 181]
```diff
@@ -23,603 +23,581 @@
...
+const w3mod = IMA.w3mod;
+const transactionCustomizerMainNet = IMA.getTransactionCustomizerForMainNet();
+const transactionCustomizerSChain = IMA.getTransactionCustomizerForSChain();
+
+const chainNameMainNet = "Mainnet";
+const chainNameSChain = "blah_blah_blah_schain_name"; // 1;
+
+// mockup for `ethersProviderSrc`
+const ethersProviderSrc = { eth: { getBlockNumber: getBlockNumber, getBlock: getBlock } };
+function getBlockNumber( string ) {
```
Comment (payvint) [inline agent/test/get_main_net.spec.js:38]: Do we need this function?

File: agent/test/get_main_net.spec.js [hunk 182]
```diff
@@ -23,603 +23,581 @@
...
+    return 2;
 }
-function getBlock(number) {
-    return {timestamp: "1469021581"}
+function getBlock( number ) {
```
Comment (payvint) [inline agent/test/get_main_net.spec.js:41]: And this function?

File: agent/test/get_main_net.spec.js [hunk 183]
```diff
@@ -23,603 +23,581 @@
  * @copyright SKALE Labs 2019-Present
```
Comment (payvint) [inline agent/test/get_main_net.spec.js]: Maybe let's rename this file to `agentUnitTests.js`

File: agent/bls.mjs [hunk 184]
```diff
@@ -0,0 +1,3130 @@
...
+    let arrBytes = imaUtils.hexToBytes( strHex );
+    if( isInvertBefore )
+        arrBytes = imaUtils.invertArrayItemsLR( arrBytes );
+    arrBytes = imaUtils.bytesAlignLeftWithZeroes( arrBytes, 32 );
+    if( isInvertAfter )
+        arrBytes = imaUtils.invertArrayItemsLR( arrBytes );
+    return arrBytes;
+}
+
+function s2ha( s ) {
```
Comment (payvint) [inline agent/bls.mjs]: Please rename to stringToKeccak256 or similar

File: agent/bls.mjs [hunk 185]
```diff
@@ -0,0 +1,3130 @@
...
+    const strU256 = owaspUtils.ethersMod.ethers.utils.id( s );
+    return hexPrepare( strU256, true, true );
+}
+
+function a2ha( arrBytes ) {
```
Comment (payvint) [inline agent/bls.mjs]: Please rename to arrayToKeccak256 or similar

File: agent/bls.mjs (hunk 45 above)
Comment (payvint) [reply agent/bls.mjs:2851]: fun of js))))

File: test/test_cases/send_ether_from_schain_to_mainnet.py (hunk 162 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_ether_from_schain_to_mainnet.py]: Done. Rolled back to `2 * 10 ** 18`. It works.

File: test/test_cases/send_erc721_from_schain_to_mainnet.py (hunk 163 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc721_from_schain_to_mainnet.py]: Done. Rolled back to `2 * 10 ** 18`. It works.

File: test/test_cases/send_erc20_from_schain_to_mainnet.py (hunk 164 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc20_from_schain_to_mainnet.py]: Done. Rolled back to `2 * 10 ** 18`. It works.

File: test/test_cases/send_erc1155_from_schain_to_mainnet.py (hunk 165 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc1155_from_schain_to_mainnet.py]: Done. Rolled back to `2 * 10 ** 18`. It works.

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py (hunk 166 above)
Comment (sergiy-skalelabs) [reply test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: Done. Rolled back to `2 * 10 ** 18`. It works.

File: agent/main.mjs
Comment (sergiy-skalelabs) [reply agent/main.mjs:1]: Yes.

File: .github/workflows/main.yml (hunk 147 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Done. Rolled back to `--gasLimit 12000000`. Command line private keys removed. It works.

File: agent/main.mjs
Comment (sergiy-skalelabs) [reply agent/main.mjs:1]: Done. Now `main.mjs` became `main.mjs` pluse `clpTools.mjs` plus `discoveryTools.mjs`. So everything is much smaller)

File: agent/utils.mjs (hunk 167 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: It's not needed at all. So I will remove it.

File: agent/utils.mjs (hunk 168 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: It's not needed at all. So I will remove it.

File: agent/main.mjs
Comment (payvint) [reply agent/main.mjs:1]: So yeah it would be simpler to read if this file would be divided by several modules, for example:
- There would be a folder `main`
- In this folder there would several files(modules) like, `registration.mjs`, `skaleNetworkBrowser.mjs`, `monitoring.mjs`, ...
- In this folder there would a `index.mjs` file where all of these modules would be imported and `main()` function would be executed

File: .eslintrc.js (hunk 23 above)
Comment (DimaStebaev) [reply .eslintrc.js:67]: As I see it's still 100.

File: .eslintrc.js [hunk 186]
```diff
@@ -60,6 +60,10 @@ module.exports = {
         "no-use-before-define": "off", // [ "error", { "variables": false,  "functions": false } ],
         "lines-between-class-members": [ "error", "never" ],
         "no-var": "error",
-        "no-unused-vars": "error"
+        "no-unused-vars": "error",
+        "object-shorthand": 0,
+        "multiline-ternary": "off",
```
Comment (DimaStebaev) [inline .eslintrc.js:65]: In my opinion a ternary operator is evil but I do not insist.

File: .github/workflows/comprehensive.yml [hunk 187]
```diff
@@ -0,0 +1,442 @@
...
+        sudo rm -rf ~/.npm || true &> /dev/null
+        sudo rm -rf ~/.node-gyp || true &> /dev/null
+        sudo rm -rf /opt/local/bin/node || true &> /dev/null
+        sudo rm -rf /opt/local/include/node || true &> /dev/null
+        sudo rm -rf /opt/local/lib/node_modules || true &> /dev/null
+        sudo rm -rf /usr/local/lib/node* || true &> /dev/null
+        sudo rm -rf /usr/local/include/node* || true &> /dev/null
+        sudo rm -rf /usr/local/bin/node* || true &> /dev/null
+
+    - name: INIT - install Node JS
```
Comment (DimaStebaev) [inline .github/workflows/comprehensive.yml:134]: There is a github action for doing this:
`actions/setup-node`

File: agent/utils.mjs (hunk 169 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs:314]: No, I cannot. Because:
1) `crypto-js` offers worst possible documentation.
2) `hexToBytes` supports `isInversiveOrder` parameter when `crypto-js` is not.

File: .github/workflows/comprehensive.yml [hunk 188]
```diff
@@ -0,0 +1,442 @@
...
+        which node
+        node --version
+        which npm
+        npm --version
+        which yarn
+        yarn --version
+        which node-gyp
+        node-gyp --version
+
+    - name: INIT - Download comprehensive-test
```
Comment (DimaStebaev) [inline .github/workflows/comprehensive.yml:155]: There is a github action for doing this:
`actions/checkout`

File: agent/utils.mjs (hunk 170 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs:335]: functions like `hexToBytes( strHex, isInversiveOrder )` and `bytesToHex( arrBytes, isInversiveOrder )` cannot be replaced with calls to libraries like `crypto-js` because:
1) `crypto-js` offers worst possible documentation.
2) `hexToBytes()` supports `isInversiveOrder` parameter when `crypto-js` is not.

File: agent/utils.mjs (hunk 171 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs:365]: I can change `bytesAlignRightWithZeroes()` to `ethers.utils.zeroPad`. But I cannot change `bytesAlignLeftWithZeroes` with anything from ``ethers.utils.*`. Nothing is offered there. Its obviously much better to keep own versions which are both simple and easy to understand.

File: .github/workflows/main.yml [hunk 189]
```diff
@@ -268,7 +265,6 @@ jobs:
         echo ------------ py3 wheel - pip
         pip3 install wheel
         echo ------------ slither analyzer install
-        # pip3 install slither-analyzer
         pip3 install slither-analyzer==0.6.8
```
Comment (DimaStebaev) [inline .github/workflows/main.yml]: It's a too old version. Use slither version from `proxy/scripts/requirements.txt`

File: npms/skale-observer/observer.mjs [hunk 190]
```diff
@@ -0,0 +1,1078 @@
...
+        if( log.verboseGet() >= log.verboseReversed().trace ) {
+            opts.details.write( cc.debug( "Have " ) + cc.info( cntSChains ) +
+                cc.debug( " S-Chain(s) to load..." ) + "\n" );
+        }
+    }
+    const arrSChains = [];
+    for( let idxSChain = 0; idxSChain < cntSChains; ++ idxSChain ) {
+        if( opts && opts.bStopNeeded )
+            break;
+        const joSChain = await loadSChain( addressFrom, idxSChain, null, cntSChains, opts );
```
Comment (payvint) [inline npms/skale-observer/observer.mjs]: You can optimize it even more, right now for 20 chains it would be 81(1*`getSchainsCount` + 20*`schainsAtSystem` + 20*`schains` 20*`getNodesInGroup` + 20*`multicall`) calls.
I will recommend to add a function `getSchainsNodes(arrayOfSchains)` which would return array of array of nodes in these chains by multi call.
And in loadSChain you can pass an array of nodes for given schain.

So before this loop 1*`getSchainsCount` + 1*`multicall(schainsAtSystem+schains)` + 1*`getSchainsNodes(...)`
And then in the loop it would be 20 multicalls of nodes data.

So by this we would do 23 calls instead of 81 calls

File: Dockerfile [hunk 191]
```diff
@@ -1,7 +1,17 @@
-FROM node:16
+FROM ubuntu:jammy
```
Comment (DimaStebaev) [inline Dockerfile:1]: Why do you install nodejs if you can use an image with already installed one?

File: npms/skale-observer/observer.mjs [hunk 192]
```diff
@@ -0,0 +1,1078 @@
...
+    if( opts && opts.details ) {
+        if( log.verboseGet() >= log.verboseReversed().trace ) {
+            opts.details.write( cc.success( "All " ) + cc.info( cntSChains ) +
+                cc.debug( " S-Chain(s) loaded:" ) + cc.j( arrSChains ) + "\n" );
+        }
+    }
+    return arrSChains;
+}
+
+export async function loadCachedSChainsSimplified( addressFrom, opts ) {
```
Comment (payvint) [inline npms/skale-observer/observer.mjs]: Here as well you can use multicall and do 2 calls instead of 21

File: agent/utils.mjs (hunk 173 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: `toArrayBuffer` is not needed at all. So I will remove it.

File: agent/utils.mjs (hunk 174 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs:398]: Agree. Will try and test.

File: npms/skale-observer/observer.mjs [hunk 193]
```diff
@@ -0,0 +1,1078 @@
...
+                addressFrom, idxSChain, strSChainHash, cntSChains, opts
+            );
+        if( ! joSChain )
+            break;
+        arrSChains.push( joSChain );
+    }
+    return arrSChains;
+}
+
+export async function loadSChainsConnectedOnly(
```
Comment (payvint) [inline npms/skale-observer/observer.mjs]: Here as well, you can do just couple multicalls:
You can load all schains and then check are they connected by multicall
Right now function is doing 21 calls on mainnet, but with multicall you can decrease the number to 2 calls:
1. getSchains
2. multicall(getSchainName)

File: agent/utils.mjs (hunk 175 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Probably yes. Will try and test.

File: agent/package.json [hunk 194]
```diff
@@ -4,19 +4,23 @@
     "license": "AGPL-3.0",
     "author": "SKALE Labs and contributors",
     "scripts": {
-        "postinstall": "echo \"----- installing in OWASP\n\" && cd ../npms/skale-owasp && yarn install && cd ../../agent && echo \"----- installing in IMA CORE\n\" && cd ../npms/skale-ima && yarn install && cd ../../agent && echo \"----- installing in IMA OBSERVER\n\" && cd ../npms/skale-observer && yarn install && cd ../../agent && echo \"----- installing in SKALE COOL SOCKET\n\" && cd ../npms/skale-cool-socket && yarn install && cd ../../agent"
+        "postinstall": "echo \"----- installing in OWASP\n\" && cd ../npms/skale-owasp && yarn install && cd ../../agent && echo \"----- installing in IMA CORE\n\" && cd ../npms/skale-ima && yarn install && cd ../../agent && echo \"----- installing in IMA OBSERVER\n\" && cd ../npms/skale-observer && yarn install && cd ../../agent && echo \"----- installing in SKALE COOL SOCKET\n\" && cd ../npms/skale-cool-socket && yarn install && cd ../../agent",
```
Comment (DimaStebaev) [inline agent/package.json]: It's much cleaner to write the script to .sh file and that call the file from here.

File: agent/utils.mjs (hunk 176 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: `TextEncoder` is present in web browser. It's not available in `node js`.

File: npms/skale-cool-socket/.eslintrc.js [hunk 195]
```diff
@@ -97,6 +97,9 @@ module.exports = {
         "no-use-before-define": "off", // [ "error", { "variables": false,  "functions": false } ],
         "lines-between-class-members": [ "error", "never" ],
         "no-var": "error",
-        "no-unused-vars": "error"
+        "no-unused-vars": "error",
```
Comment (DimaStebaev) [inline npms/skale-cool-socket/.eslintrc.js]: Why don't use the config from a parent folder?

File: agent/pwa.mjs (hunk 177 above)
Comment (sergiy-skalelabs) [reply agent/pwa.mjs]: Done.

File: agent/rpcCall.mjs (hunk 178 above)
Comment (sergiy-skalelabs) [reply agent/rpcCall.mjs]: Done.

File: agent/bls.mjs (hunk 184 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done.

File: agent/bls.mjs (hunk 185 above)
Comment (sergiy-skalelabs) [reply agent/bls.mjs]: Done.

File: proxy/predeployed/src/ima_predeployed/contract_generator.py
Comment (DimaStebaev) [inline proxy/predeployed/src/ima_predeployed/contract_generator.py:1]: I'm not sure that this is relevant for the pull request but this file has to be removed because it's present in the `predeployed-generator` package.

File: agent/utils.mjs (hunk 172 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Yes, agree. Done.

File: test/test_cases/send_erc1155_batch_from_schain_to_mainnet.py [hunk 196]
```diff
@@ -35,8 +35,10 @@ def __init__(self, config):
         super().__init__('Send ERC1155 Batch from schain to mainnet', config)
 
     def _prepare(self):
-        amount = 2 * 10 ** 18
-        self.blockchain.recharge_user_wallet(self.config.mainnet_key, self.config.schain_name, amount)
+        sleep( 5 )
+        amountRecharge = 2 * 10 ** 18 # 2 * 10 ** 18
```
Comment (DimaStebaev) [inline test/test_cases/send_erc1155_batch_from_schain_to_mainnet.py]: It's the most useful comment I've ever seen. (-:

File: test/test_cases/send_ether_from_schain_to_mainnet.py [hunk 197]
```diff
@@ -64,12 +68,22 @@ def _execute(self):
                                                        self.config.schain_key,
                                                        self.amount,
                                                        self.timeout)
+        sleep( 5 )
 
         transaction_fee = 6 * 10 ** 16
         approximate_gas_spends = 3 * 10 ** 15
-        if self.blockchain.get_balance_on_mainnet(destination_address) > (
-                balance + self.amount - transaction_fee - approximate_gas_spends):
+        extra_subtract_value = 1 * 10 ** 17 # 0
```
Comment (DimaStebaev) [inline test/test_cases/send_ether_from_schain_to_mainnet.py]: I think the comment has to be `0.1 * 10 ** 18` (-:

File: agent/utils.mjs (hunk 174 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs:398]: Works. Done,

File: agent/utils.mjs (hunk 175 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Works. Done.

File: .eslintrc.js (hunk 186 above)
Comment (sergiy-skalelabs) [reply .eslintrc.js:65]: Kernighan and Ritchie

File: .github/workflows/comprehensive.yml (hunk 187 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml:134]: If you cannot install node then you should not use it at all. Github can go to hell in this case.

File: .github/workflows/comprehensive.yml (hunk 188 above)
Comment (sergiy-skalelabs) [reply .github/workflows/comprehensive.yml:155]: Same as previous.

File: Dockerfile (hunk 191 above)
Comment (sergiy-skalelabs) [reply Dockerfile:1]: If you cannot install node js then you should not use it at all. Is node js as `node` command line tool worst of creating separated OS image? I think it's strange to download container image when I need one command line app.

File: test/test_cases/send_ether_from_schain_to_mainnet.py (hunk 197 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_ether_from_schain_to_mainnet.py]: Removed. Thanks.

File: test/test_cases/send_erc1155_batch_from_schain_to_mainnet.py (hunk 196 above)
Comment (sergiy-skalelabs) [reply test/test_cases/send_erc1155_batch_from_schain_to_mainnet.py]: Removed. Thanks.

File: agent/utils.mjs (hunk 171 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs:365]: Rewritten. Simplified. No `for`/`while` loops.

File: agent/utils.mjs (hunk 172 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Rewritten. Simplified. No `for`/`while` loops.

File: agent/utils.mjs (hunk 176 above)
Comment (sergiy-skalelabs) [reply agent/utils.mjs]: Not needed at all. Both `ab2str` and `str2ab` are unused. Will remove them. Thanks.

File: agent/CLI.md (hunk 179 above)
Comment (sergiy-skalelabs) [reply agent/CLI.md:197]: We have consistent and always present opposite options like `skip-dry-run` and `no-skip-dry-run` like many command line problems in Unix. Even of one of them is default behavior and never needed to specify. Not our invention. Default is `no-skip-dry-run` if nothing is specified.
The reason for this is to catch attention on what is invoked on command line. 
We also have `ignore-dry-run` and `no-ignore-dry-run`. Default is `ignore-dry-run` because it un-successful in some of Ethereum calls IMA does.
Having `no-skip-dry-run` and `ignore-dry-run` together allows us to see problems in logs.

File: test/agent/agent.py (hunk 180 above)
Comment (sergiy-skalelabs) [reply test/agent/agent.py]: Yes, PY-tests run IMA Agent colorized.
Both `skip-dry-run` and `no-skip-dry-run` are not outdated.
Both `ignore-dry-run` and `no-ignore-dry-run` are not outdated too.

File: agent/test/get_main_net.spec.js (hunk 183 above)
Comment (sergiy-skalelabs) [reply agent/test/get_main_net.spec.js]: Will rename. Thanks.

File: .github/workflows/main.yml (hunk 189 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: Will do it. Thanks.

File: proxy/predeployed/src/ima_predeployed/contract_generator.py
Comment (sergiy-skalelabs) [reply proxy/predeployed/src/ima_predeployed/contract_generator.py:1]: We need to figure out how it appear here)

File: npms/skale-cool-socket/.eslintrc.js (hunk 195 above)
Comment (sergiy-skalelabs) [reply npms/skale-cool-socket/.eslintrc.js]: Yes, you are right. One is enough.

File: agent/package.json (hunk 194 above)
Comment (sergiy-skalelabs) [reply agent/package.json]: Done.

File: npms/skale-ima/index.mjs [hunk 198]
```diff
@@ -0,0 +1,7643 @@
+// SPDX-License-Identifier: AGPL-3.0-only
```
Comment (payvint) [inline npms/skale-ima/index.mjs]: if you can divide this file to several small specific files(erc20Transfers, erc721Transfers, oracleOperations, ...) - it would be much more readable!

**Review by payvint — COMMENTED** [review]
Everything looks good!
Just to fix some small items!

File: npms/skale-ima/index.mjs (hunk 198 above)
Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Yes.

Comment (sergiy-skalelabs) [reply npms/skale-ima/index.mjs]: Done.

File: .github/workflows/main.yml [hunk 199]
```diff
@@ -268,8 +265,7 @@ jobs:
         echo ------------ py3 wheel - pip
         pip3 install wheel
         echo ------------ slither analyzer install
-        # pip3 install slither-analyzer
-        pip3 install slither-analyzer==0.6.8
+        pip3 install slither-analyzer==0.8.3
```
Comment (DimaStebaev) [inline .github/workflows/main.yml]: `pip3 install -r proxy/scripts/requirements.txt`

**Review by DimaStebaev — DISMISSED** [review]

File: .github/workflows/main.yml (hunk 199 above)
Comment (sergiy-skalelabs) [reply .github/workflows/main.yml]: OK, will try

File: npms/skale-observer/observer.mjs (hunk 190 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Done

File: npms/skale-observer/observer.mjs (hunk 192 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Done

File: npms/skale-observer/observer.mjs (hunk 193 above)
Comment (sergiy-skalelabs) [reply npms/skale-observer/observer.mjs]: Done

File: proxy/predeployed/src/ima_predeployed/contract_generator.py
Comment (DimaStebaev) [reply proxy/predeployed/src/ima_predeployed/contract_generator.py:1]: I've created the an issue #1484

**Review by DimaStebaev — APPROVED** [review]

File: test/tools/test_case.py (hunk 160 above)
Comment (payvint) [reply test/tools/test_case.py]: I see, timeout is passing to the agent functions - and a timeout of some operation

And you just added a timout_of_entire_test

File: test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py (hunk 157 above)
Comment (payvint) [reply test/test_cases/load_send_ether_from_mainnet_to_schain_and_back.py]: Fixed

**Review by payvint — APPROVED** [review]
Let's give it a shot!

**Review by cstrangedk — APPROVED** [review]
